# TCGA-BRCA Clinical Biotab Review

This notebook reviews parsed TCGA-BRCA Clinical Supplement biotab tables from disk only.
It is validation-oriented and remains part of source audit rather than cohort construction.

## Load the latest saved clinical biotab parse run

In [1]:
from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
from IPython.display import display


def find_repo_root(start: Path) -> Path:
    for candidate in [start, *start.parents]:
        if (candidate / ".git").exists():
            return candidate
    raise FileNotFoundError("Could not locate the repository root from the current working directory.")


repo_root = find_repo_root(Path.cwd())
latest_pointer_path = (
    repo_root / "01-data" / "audit" / "tcga-brca" / "variables" / "tcga_brca_clinical_biotabs_latest.json"
)
if not latest_pointer_path.exists():
    raise FileNotFoundError(
        f"Latest clinical biotab pointer not found: {latest_pointer_path}. Run the parsing script first."
    )

latest_pointer = json.loads(latest_pointer_path.read_text(encoding="utf-8"))
manifest_path = repo_root / latest_pointer["table_manifest_tsv"]
run_log_path = repo_root / latest_pointer["run_log_json"]
results_root = repo_root / "09-trials" / "01-tcga-only-source-audited" / "05-results"
results_root.mkdir(parents=True, exist_ok=True)

display(pd.DataFrame([latest_pointer]))

,updated_at_utc,parse_run_id,source_run_id,processed_run_directory,audit_run_directory,table_manifest_tsv,run_log_json,source_supplement_latest_json,source_metadata_tsv,parsed_table_count
0,2026-04-12T01:09:32Z,20260412T010932Z,20260412T000556Z,01-data/processed/tcga-brca/clinical/biotab_ru...,01-data/audit/tcga-brca/variables/clinical_bio...,01-data/audit/tcga-brca/variables/clinical_bio...,01-data/audit/tcga-brca/variables/clinical_bio...,01-data/audit/tcga-brca/source/tcga_brca_sourc...,01-data/audit/tcga-brca/source/supplements/run...,9

## Load the saved manifest and run log

In [2]:
manifest_df = pd.read_csv(manifest_path, sep="\t")
run_log = json.loads(run_log_path.read_text(encoding="utf-8"))

print(f"Manifest TSV: {manifest_path}")
print(f"Run log: {run_log_path}")
print(f"Tables listed: {len(manifest_df)}")
display(manifest_df)

Manifest TSV: D:\Projects\brcapath-rx\01-data\audit\tcga-brca\variables\clinical_biotab_runs\20260412T010932Z\clinical_biotab_table_manifest.tsv
Run log: D:\Projects\brcapath-rx\01-data\audit\tcga-brca\variables\clinical_biotab_runs\20260412T010932Z\run_log.json
Tables listed: 9

,parse_run_id,source_run_id,source_class,table_name,source_file_id,source_filename,source_path,output_filename,output_path,schema_path,row_count,column_count,header_preamble_rows,data_start_line,parse_notes
0,20260412T010932Z,20260412T000556Z,clinical,clinical_drug,1e6b79ff-9787-4cbe-b19d-ebabb6b43589,nationwidechildrens.org_clinical_drug_brca.txt,01-data/raw/tcga-brca/gdc/downloads/clinical/2...,clinical_drug.tsv,01-data/processed/tcga-brca/clinical/biotab_ru...,01-data/audit/tcga-brca/variables/clinical_bio...,2406,28,3,4,Primary TSV preserves source line-1 headers ex...
1,20260412T010932Z,20260412T000556Z,clinical,clinical_follow_up_v1_5,22f38342-3f1a-47e5-9025-c19719fa21d0,nationwidechildrens.org_clinical_follow_up_v1....,01-data/raw/tcga-brca/gdc/downloads/clinical/2...,clinical_follow_up_v1_5.tsv,01-data/processed/tcga-brca/clinical/biotab_ru...,01-data/audit/tcga-brca/variables/clinical_bio...,114,63,3,4,Primary TSV preserves source line-1 headers ex...
2,20260412T010932Z,20260412T000556Z,clinical,clinical_follow_up_v2_1,403b5cef-8173-47c7-b56a-cc94dcfbb2e3,nationwidechildrens.org_clinical_follow_up_v2....,01-data/raw/tcga-brca/gdc/downloads/clinical/2...,clinical_follow_up_v2_1.tsv,01-data/processed/tcga-brca/clinical/biotab_ru...,01-data/audit/tcga-brca/variables/clinical_bio...,523,45,3,4,Primary TSV preserves source line-1 headers ex...
3,20260412T010932Z,20260412T000556Z,clinical,clinical_follow_up_v4_0,62d4515f-a30b-4b1a-b2dd-c8bf9476e803,nationwidechildrens.org_clinical_follow_up_v4....,01-data/raw/tcga-brca/gdc/downloads/clinical/2...,clinical_follow_up_v4_0.tsv,01-data/processed/tcga-brca/clinical/biotab_ru...,01-data/audit/tcga-brca/variables/clinical_bio...,716,13,3,4,Primary TSV preserves source line-1 headers ex...
4,20260412T010932Z,20260412T000556Z,clinical,clinical_follow_up_v4_0_nte,a9baecf0-5549-4396-8805-a6d1681d11cd,nationwidechildrens.org_clinical_follow_up_v4....,01-data/raw/tcga-brca/gdc/downloads/clinical/2...,clinical_follow_up_v4_0_nte.tsv,01-data/processed/tcga-brca/clinical/biotab_ru...,01-data/audit/tcga-brca/variables/clinical_bio...,82,35,3,4,Primary TSV preserves source line-1 headers ex...
5,20260412T010932Z,20260412T000556Z,clinical,clinical_nte,a88c168e-4bba-4bd2-9c0c-77934444cc1c,nationwidechildrens.org_clinical_nte_brca.txt,01-data/raw/tcga-brca/gdc/downloads/clinical/2...,clinical_nte.tsv,01-data/processed/tcga-brca/clinical/biotab_ru...,01-data/audit/tcga-brca/variables/clinical_bio...,119,34,3,4,Primary TSV preserves source line-1 headers ex...
6,20260412T010932Z,20260412T000556Z,clinical,clinical_omf_v4_0,f434b393-9e32-4ca2-aa1a-3b0de36b5ffe,nationwidechildrens.org_clinical_omf_v4.0_brca...,01-data/raw/tcga-brca/gdc/downloads/clinical/2...,clinical_omf_v4_0.tsv,01-data/processed/tcga-brca/clinical/biotab_ru...,01-data/audit/tcga-brca/variables/clinical_bio...,82,30,3,4,Primary TSV preserves source line-1 headers ex...
7,20260412T010932Z,20260412T000556Z,clinical,clinical_patient,8162d394-8b64-4da2-9f5b-d164c54b9608,nationwidechildrens.org_clinical_patient_brca.txt,01-data/raw/tcga-brca/gdc/downloads/clinical/2...,clinical_patient.tsv,01-data/processed/tcga-brca/clinical/biotab_ru...,01-data/audit/tcga-brca/variables/clinical_bio...,1097,112,3,4,Primary TSV preserves source line-1 headers ex...
8,20260412T010932Z,20260412T000556Z,clinical,clinical_radiation,0a40467f-9495-4c5b-b56e-3347a3ee0572,nationwidechildrens.org_clinical_radiation_brc...,01-data/raw/tcga-brca/gdc/downloads/clinical/2...,clinical_radiation.tsv,01-data/processed/tcga-brca/clinical/biotab_ru...,01-data/audit/tcga-brca/variables/clinical_bio...,618,18,3,4,Primary TSV preserves source line-1 headers ex...

## Table inventory, source-file mapping, and shape checks

In [3]:
parsed_tables = {}
summary_rows = []

for row in manifest_df.to_dict(orient="records"):
    table_path = repo_root / row["output_path"]
    table_df = pd.read_csv(table_path, sep="\t", dtype=str, keep_default_na=False, na_filter=False)
    parsed_tables[row["table_name"]] = table_df
    summary_rows.append(
        {
            "parse_run_id": row["parse_run_id"],
            "source_run_id": row["source_run_id"],
            "table_name": row["table_name"],
            "source_filename": row["source_filename"],
            "output_filename": row["output_filename"],
            "row_count": int(len(table_df)),
            "column_count": int(len(table_df.columns)),
            "manifest_row_count": int(row["row_count"]),
            "manifest_column_count": int(row["column_count"]),
            "row_count_matches_manifest": bool(len(table_df) == int(row["row_count"])),
            "column_count_matches_manifest": bool(len(table_df.columns) == int(row["column_count"])),
            "source_path": row["source_path"],
            "output_path": row["output_path"],
        }
    )

summary_df = pd.DataFrame(summary_rows).sort_values("table_name").reset_index(drop=True)
summary_path = results_root / "15_clinical_biotab_table_summary.tsv"
summary_df.to_csv(summary_path, sep="\t", index=False)

print(f"Saved: {summary_path}")
display(summary_df)

Saved: D:\Projects\brcapath-rx\09-trials\01-tcga-only-source-audited\05-results\15_clinical_biotab_table_summary.tsv

,parse_run_id,source_run_id,table_name,source_filename,output_filename,row_count,column_count,manifest_row_count,manifest_column_count,row_count_matches_manifest,column_count_matches_manifest,source_path,output_path
0,20260412T010932Z,20260412T000556Z,clinical_drug,nationwidechildrens.org_clinical_drug_brca.txt,clinical_drug.tsv,2406,28,2406,28,True,True,01-data/raw/tcga-brca/gdc/downloads/clinical/2...,01-data/processed/tcga-brca/clinical/biotab_ru...
1,20260412T010932Z,20260412T000556Z,clinical_follow_up_v1_5,nationwidechildrens.org_clinical_follow_up_v1....,clinical_follow_up_v1_5.tsv,114,63,114,63,True,True,01-data/raw/tcga-brca/gdc/downloads/clinical/2...,01-data/processed/tcga-brca/clinical/biotab_ru...
2,20260412T010932Z,20260412T000556Z,clinical_follow_up_v2_1,nationwidechildrens.org_clinical_follow_up_v2....,clinical_follow_up_v2_1.tsv,523,45,523,45,True,True,01-data/raw/tcga-brca/gdc/downloads/clinical/2...,01-data/processed/tcga-brca/clinical/biotab_ru...
3,20260412T010932Z,20260412T000556Z,clinical_follow_up_v4_0,nationwidechildrens.org_clinical_follow_up_v4....,clinical_follow_up_v4_0.tsv,716,13,716,13,True,True,01-data/raw/tcga-brca/gdc/downloads/clinical/2...,01-data/processed/tcga-brca/clinical/biotab_ru...
4,20260412T010932Z,20260412T000556Z,clinical_follow_up_v4_0_nte,nationwidechildrens.org_clinical_follow_up_v4....,clinical_follow_up_v4_0_nte.tsv,82,35,82,35,True,True,01-data/raw/tcga-brca/gdc/downloads/clinical/2...,01-data/processed/tcga-brca/clinical/biotab_ru...
5,20260412T010932Z,20260412T000556Z,clinical_nte,nationwidechildrens.org_clinical_nte_brca.txt,clinical_nte.tsv,119,34,119,34,True,True,01-data/raw/tcga-brca/gdc/downloads/clinical/2...,01-data/processed/tcga-brca/clinical/biotab_ru...
6,20260412T010932Z,20260412T000556Z,clinical_omf_v4_0,nationwidechildrens.org_clinical_omf_v4.0_brca...,clinical_omf_v4_0.tsv,82,30,82,30,True,True,01-data/raw/tcga-brca/gdc/downloads/clinical/2...,01-data/processed/tcga-brca/clinical/biotab_ru...
7,20260412T010932Z,20260412T000556Z,clinical_patient,nationwidechildrens.org_clinical_patient_brca.txt,clinical_patient.tsv,1097,112,1097,112,True,True,01-data/raw/tcga-brca/gdc/downloads/clinical/2...,01-data/processed/tcga-brca/clinical/biotab_ru...
8,20260412T010932Z,20260412T000556Z,clinical_radiation,nationwidechildrens.org_clinical_radiation_brc...,clinical_radiation.tsv,618,18,618,18,True,True,01-data/raw/tcga-brca/gdc/downloads/clinical/2...,01-data/processed/tcga-brca/clinical/biotab_ru...

## Column-name review and field-group presence

This section summarizes major field groups by column name only and does not interpret the values.

In [4]:
FIELD_GROUP_PATTERNS = {
    "demographics": ["gender", "race", "ethnicity", "menopause", "birth", "age"],
    "stage": ["ajcc", "stage", "clinical_t", "clinical_n", "clinical_m", "pathologic", "diagnosis"],
    "receptor": ["er_", "pr_", "her2", "receptor"],
    "drug": ["drug", "pharm", "pharmaceutical", "regimen", "therapy_type"],
    "radiation": ["radiation", "rt_", "irradiat"],
    "follow_up": ["follow_up", "followup", "last_contact", "vital_status", "death_days", "days_to_death"],
    "new_tumor_event": ["new_tumor_event", "new_neoplasm", "nte_"],
    "pathology": ["histolog", "margin", "lymph", "tumor_status", "subdivision"],
}

field_group_rows = []
for table_name, table_df in parsed_tables.items():
    column_names = list(table_df.columns)
    lower_names = [name.lower() for name in column_names]
    for field_group, patterns in FIELD_GROUP_PATTERNS.items():
        matched_columns = [
            column_names[index]
            for index, lower_name in enumerate(lower_names)
            if any(pattern in lower_name for pattern in patterns)
        ]
        field_group_rows.append(
            {
                "table_name": table_name,
                "field_group": field_group,
                "matched_column_count": len(matched_columns),
                "matched_columns": json.dumps(matched_columns, ensure_ascii=True),
            }
        )

field_group_df = pd.DataFrame(field_group_rows).sort_values(["table_name", "field_group"]).reset_index(drop=True)
field_group_path = results_root / "16_clinical_biotab_field_group_presence.tsv"
field_group_df.to_csv(field_group_path, sep="\t", index=False)

print(f"Saved: {field_group_path}")
display(field_group_df)

Saved: D:\Projects\brcapath-rx\09-trials\01-tcga-only-source-audited\05-results\16_clinical_biotab_field_group_presence.tsv

,table_name,field_group,matched_column_count,matched_columns
0,clinical_drug,demographics,0,[]
1,clinical_drug,drug,17,"[""bcr_drug_barcode"", ""bcr_drug_uuid"", ""pharmac..."
2,clinical_drug,follow_up,0,[]
3,clinical_drug,new_tumor_event,0,[]
4,clinical_drug,pathology,0,[]
...,...,...,...,...
67,clinical_radiation,new_tumor_event,0,[]
68,clinical_radiation,pathology,0,[]
69,clinical_radiation,radiation,11,"[""bcr_radiation_barcode"", ""bcr_radiation_uuid""..."
70,clinical_radiation,receptor,0,[]
71,clinical_radiation,stage,0,[]

## Missingness-like token review

This section counts common placeholder tokens directly from the parsed tables without changing the source values.

In [5]:
MISSING_LIKE_TOKENS = {
    "blank": "",
    "not_available": "[Not Available]",
    "not_applicable": "[Not Applicable]",
    "unknown": "[Unknown]",
    "not_evaluated": "[Not Evaluated]",
    "discrepancy": "[Discrepancy]",
}

missingness_rows = []
for table_name, table_df in parsed_tables.items():
    row_count = len(table_df)
    for column_name in table_df.columns:
        values = table_df[column_name].astype(str)
        token_counts = {label: int((values == token).sum()) for label, token in MISSING_LIKE_TOKENS.items()}
        missing_like_count = sum(token_counts.values())
        missingness_rows.append(
            {
                "table_name": table_name,
                "column_name": column_name,
                "row_count": int(row_count),
                "blank_count": token_counts["blank"],
                "not_available_count": token_counts["not_available"],
                "not_applicable_count": token_counts["not_applicable"],
                "unknown_count": token_counts["unknown"],
                "not_evaluated_count": token_counts["not_evaluated"],
                "discrepancy_count": token_counts["discrepancy"],
                "missing_like_count": missing_like_count,
                "missing_like_fraction": float(missing_like_count / row_count) if row_count else 0.0,
            }
        )

missingness_df = (
    pd.DataFrame(missingness_rows)
    .sort_values(["table_name", "missing_like_fraction", "column_name"], ascending=[True, False, True])
    .reset_index(drop=True)
)
missingness_path = results_root / "17_clinical_biotab_missingness_summary.tsv"
missingness_df.to_csv(missingness_path, sep="\t", index=False)

print(f"Saved: {missingness_path}")
display(missingness_df.head(25))

Saved: D:\Projects\brcapath-rx\09-trials\01-tcga-only-source-audited\05-results\17_clinical_biotab_missingness_summary.tsv

,table_name,column_name,row_count,blank_count,not_available_count,not_applicable_count,unknown_count,not_evaluated_count,discrepancy_count,missing_like_count,missing_like_fraction
0,clinical_drug,days_to_stem_cell_transplantation,2406,0,2406,0,0,0,0,2406,1.000000
1,clinical_drug,pharm_regimen,2406,0,2406,0,0,0,0,2406,1.000000
2,clinical_drug,pharm_regimen_other,2406,0,2406,0,0,0,0,2406,1.000000
3,clinical_drug,stem_cell_transplantation,2406,0,2406,0,0,0,0,2406,1.000000
4,clinical_drug,stem_cell_transplantation_type,2406,0,2406,0,0,0,0,2406,1.000000
5,clinical_drug,therapy_regimen_other,2406,0,0,2393,0,0,0,2393,0.994597
6,clinical_drug,pharma_type_other,2406,0,2384,0,0,0,0,2384,0.990856
7,clinical_drug,clinical_trial_drug_classification,2406,0,2285,0,0,0,0,2285,0.949709
8,clinical_drug,treatment_best_response,2406,0,1455,176,126,0,4,1761,0.731920
9,clinical_drug,total_dose,2406,0,1629,0,0,0,0,1629,0.677057
10,clinical_drug,pharmaceutical_tx_total_dose_units,2406,0,1555,0,0,0,0,1555,0.646301
11,clinical_drug,pharma_adjuvant_cycles_count,2406,0,1543,0,0,0,0,1543,0.641313
12,clinical_drug,tx_on_clinical_trial,2406,0,1321,0,0,0,0,1321,0.549044
13,clinical_drug,prescribed_dose,2406,0,1278,0,0,0,0,1278,0.531172
14,clinical_drug,regimen_number,2406,0,1265,0,1,0,0,1266,0.526185
15,clinical_drug,pharmaceutical_tx_dose_units,2406,0,1265,0,0,0,0,1265,0.525769
16,clinical_drug,route_of_administration,2406,0,1163,0,0,0,0,1163,0.483375
17,clinical_drug,therapy_regimen,2406,0,1090,0,0,0,0,1090,0.453034
18,clinical_drug,pharmaceutical_tx_ended_days_to,2406,0,601,0,0,0,0,601,0.249792
19,clinical_drug,pharmaceutical_tx_started_days_to,2406,0,116,0,0,0,2,118,0.049044
20,clinical_drug,pharmaceutical_therapy_drug_name,2406,0,15,0,1,0,0,16,0.006650
21,clinical_drug,pharmaceutical_tx_ongoing_indicator,2406,0,15,0,0,0,0,15,0.006234
22,clinical_drug,pharmaceutical_therapy_type,2406,0,7,0,0,0,0,7,0.002909
23,clinical_drug,bcr_drug_barcode,2406,0,0,0,0,0,0,0,0.000000
24,clinical_drug,bcr_drug_uuid,2406,0,0,0,0,0,0,0,0.000000

## Review reminder

These outputs stay at the source-audit layer. They do not define a final cohort, endpoint, or modeling-ready clinical table.