# TCGA-BRCA Biospecimen Biotab Review

This notebook reviews parsed TCGA-BRCA core Biospecimen Supplement biotab tables from disk only.
It is validation-oriented and remains part of source audit rather than cohort construction.

## Load the latest saved biospecimen biotab parse run

In [1]:
from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
from IPython.display import display


def find_repo_root(start: Path) -> Path:
    for candidate in [start, *start.parents]:
        if (candidate / ".git").exists():
            return candidate
    raise FileNotFoundError("Could not locate the repository root from the current working directory.")


repo_root = find_repo_root(Path.cwd())
latest_pointer_path = (
    repo_root / "01-data" / "audit" / "tcga-brca" / "variables" / "tcga_brca_biospecimen_biotabs_latest.json"
)
if not latest_pointer_path.exists():
    raise FileNotFoundError(
        f"Latest biospecimen biotab pointer not found: {latest_pointer_path}. Run the parsing script first."
    )

latest_pointer = json.loads(latest_pointer_path.read_text(encoding="utf-8"))
manifest_path = repo_root / latest_pointer["table_manifest_tsv"]
source_inventory_path = repo_root / latest_pointer["source_inventory_tsv"]
run_log_path = repo_root / latest_pointer["run_log_json"]
results_root = repo_root / "09-trials" / "01-tcga-only-source-audited" / "05-results"
results_root.mkdir(parents=True, exist_ok=True)

display(pd.DataFrame([latest_pointer]))

,updated_at_utc,parse_run_id,source_run_id,processed_run_directory,audit_run_directory,source_inventory_tsv,table_manifest_tsv,run_log_json,source_supplement_latest_json,source_metadata_tsv,parsed_table_count,discovered_biotab_file_count,excluded_biotab_file_count
0,2026-04-13T07:04:00Z,20260413T070359Z,20260412T000556Z,01-data/processed/tcga-brca/biospecimen/biotab...,01-data/audit/tcga-brca/variables/biospecimen_...,01-data/audit/tcga-brca/variables/biospecimen_...,01-data/audit/tcga-brca/variables/biospecimen_...,01-data/audit/tcga-brca/variables/biospecimen_...,01-data/audit/tcga-brca/source/tcga_brca_sourc...,01-data/audit/tcga-brca/source/supplements/run...,8,10,2

## Load the saved source inventory, manifest, and run log

The source inventory should show the discovered core biospecimen biotabs plus the deferred `ssf_*.txt` text tables.

In [2]:
source_inventory_df = pd.read_csv(source_inventory_path, sep="\t", dtype=str, keep_default_na=False, na_filter=False)
manifest_df = pd.read_csv(manifest_path, sep="\t", dtype=str, keep_default_na=False, na_filter=False)
run_log = json.loads(run_log_path.read_text(encoding="utf-8"))

print(f"Source inventory TSV: {source_inventory_path}")
print(f"Manifest TSV: {manifest_path}")
print(f"Run log: {run_log_path}")
print(f"Discovered biospecimen biotab text files: {len(source_inventory_df)}")
print(f"Parsed tables listed: {len(manifest_df)}")
display(source_inventory_df)
display(manifest_df)

Source inventory TSV: D:\Projects\brcapath-rx\01-data\audit\tcga-brca\variables\biospecimen_biotab_runs\20260413T070359Z\biospecimen_biotab_source_inventory.tsv
Manifest TSV: D:\Projects\brcapath-rx\01-data\audit\tcga-brca\variables\biospecimen_biotab_runs\20260413T070359Z\biospecimen_biotab_table_manifest.tsv
Run log: D:\Projects\brcapath-rx\01-data\audit\tcga-brca\variables\biospecimen_biotab_runs\20260413T070359Z\run_log.json
Discovered biospecimen biotab text files: 10
Parsed tables listed: 8

,parse_run_id,source_run_id,source_class,source_file_id,source_filename,source_path,data_format,case_count,scope_status,scope_reason,table_name,output_filename
0,20260413T070359Z,20260412T000556Z,biospecimen,950ee56c-df20-4b39-867e-c73f17d0f4f6,nationwidechildrens.org_biospecimen_aliquot_br...,01-data/raw/tcga-brca/gdc/downloads/biospecime...,BCR Biotab,1098,parsed,Core biospecimen hierarchy biotab table includ...,biospecimen_aliquot,biospecimen_aliquot.tsv
1,20260413T070359Z,20260412T000556Z,biospecimen,d0c967b5-78ee-4bc4-9493-3cbe44af1bf5,nationwidechildrens.org_biospecimen_analyte_br...,01-data/raw/tcga-brca/gdc/downloads/biospecime...,BCR Biotab,1098,parsed,Core biospecimen hierarchy biotab table includ...,biospecimen_analyte,biospecimen_analyte.tsv
2,20260413T070359Z,20260412T000556Z,biospecimen,edbb5de2-d0b5-4a07-a0e1-19e952a5117d,nationwidechildrens.org_biospecimen_diagnostic...,01-data/raw/tcga-brca/gdc/downloads/biospecime...,BCR Biotab,1098,parsed,Core biospecimen hierarchy biotab table includ...,biospecimen_diagnostic_slides,biospecimen_diagnostic_slides.tsv
3,20260413T070359Z,20260412T000556Z,biospecimen,22656b71-476a-4b5f-9f3b-82afb29a34bc,nationwidechildrens.org_biospecimen_portion_br...,01-data/raw/tcga-brca/gdc/downloads/biospecime...,BCR Biotab,1098,parsed,Core biospecimen hierarchy biotab table includ...,biospecimen_portion,biospecimen_portion.tsv
4,20260413T070359Z,20260412T000556Z,biospecimen,a24d7574-e419-47ce-9293-b9b29f854a10,nationwidechildrens.org_biospecimen_protocol_b...,01-data/raw/tcga-brca/gdc/downloads/biospecime...,BCR Biotab,1098,parsed,Core biospecimen hierarchy biotab table includ...,biospecimen_protocol,biospecimen_protocol.tsv
5,20260413T070359Z,20260412T000556Z,biospecimen,c5039e7e-14d8-4e59-ba20-0d3fa38b86df,nationwidechildrens.org_biospecimen_sample_brc...,01-data/raw/tcga-brca/gdc/downloads/biospecime...,BCR Biotab,1098,parsed,Core biospecimen hierarchy biotab table includ...,biospecimen_sample,biospecimen_sample.tsv
6,20260413T070359Z,20260412T000556Z,biospecimen,43569ab9-5a32-45ef-a07e-e93f45416a16,nationwidechildrens.org_biospecimen_shipment_p...,01-data/raw/tcga-brca/gdc/downloads/biospecime...,BCR Biotab,1098,parsed,Core biospecimen hierarchy biotab table includ...,biospecimen_shipment_portion,biospecimen_shipment_portion.tsv
7,20260413T070359Z,20260412T000556Z,biospecimen,c10090b8-fa42-4e32-86a0-9dedceb5b605,nationwidechildrens.org_biospecimen_slide_brca...,01-data/raw/tcga-brca/gdc/downloads/biospecime...,BCR Biotab,1098,parsed,Core biospecimen hierarchy biotab table includ...,biospecimen_slide,biospecimen_slide.tsv
8,20260413T070359Z,20260412T000556Z,biospecimen,5907be67-69f6-4339-8264-952a2462bea5,nationwidechildrens.org_ssf_normal_controls_br...,01-data/raw/tcga-brca/gdc/downloads/biospecime...,BCR Biotab,1098,excluded,Deferred in v1: SSF text biotab tables are out...,,
9,20260413T070359Z,20260412T000556Z,biospecimen,41fd4c6c-2932-4c6b-914f-7abaea9dc8a0,nationwidechildrens.org_ssf_tumor_samples_brca...,01-data/raw/tcga-brca/gdc/downloads/biospecime...,BCR Biotab,1098,excluded,Deferred in v1: SSF text biotab tables are out...,,

,parse_run_id,source_run_id,source_class,table_name,source_file_id,source_filename,source_path,output_filename,output_path,schema_path,row_count,column_count,header_preamble_rows,data_start_line,parse_notes
0,20260413T070359Z,20260412T000556Z,biospecimen,biospecimen_aliquot,950ee56c-df20-4b39-867e-c73f17d0f4f6,nationwidechildrens.org_biospecimen_aliquot_br...,01-data/raw/tcga-brca/gdc/downloads/biospecime...,biospecimen_aliquot.tsv,01-data/processed/tcga-brca/biospecimen/biotab...,01-data/audit/tcga-brca/variables/biospecimen_...,14538,15,2,3,Primary TSV preserves source line-1 headers ex...
1,20260413T070359Z,20260412T000556Z,biospecimen,biospecimen_analyte,d0c967b5-78ee-4bc4-9493-3cbe44af1bf5,nationwidechildrens.org_biospecimen_analyte_br...,01-data/raw/tcga-brca/gdc/downloads/biospecime...,biospecimen_analyte.tsv,01-data/processed/tcga-brca/biospecimen/biotab...,01-data/audit/tcga-brca/variables/biospecimen_...,6315,17,2,3,Primary TSV preserves source line-1 headers ex...
2,20260413T070359Z,20260412T000556Z,biospecimen,biospecimen_diagnostic_slides,edbb5de2-d0b5-4a07-a0e1-19e952a5117d,nationwidechildrens.org_biospecimen_diagnostic...,01-data/raw/tcga-brca/gdc/downloads/biospecime...,biospecimen_diagnostic_slides.tsv,01-data/processed/tcga-brca/biospecimen/biotab...,01-data/audit/tcga-brca/variables/biospecimen_...,1142,4,2,3,Primary TSV preserves source line-1 headers ex...
3,20260413T070359Z,20260412T000556Z,biospecimen,biospecimen_portion,22656b71-476a-4b5f-9f3b-82afb29a34bc,nationwidechildrens.org_biospecimen_portion_br...,01-data/raw/tcga-brca/gdc/downloads/biospecime...,biospecimen_portion.tsv,01-data/processed/tcga-brca/biospecimen/biotab...,01-data/audit/tcga-brca/variables/biospecimen_...,2310,10,2,3,Primary TSV preserves source line-1 headers ex...
4,20260413T070359Z,20260412T000556Z,biospecimen,biospecimen_protocol,a24d7574-e419-47ce-9293-b9b29f854a10,nationwidechildrens.org_biospecimen_protocol_b...,01-data/raw/tcga-brca/gdc/downloads/biospecime...,biospecimen_protocol.tsv,01-data/processed/tcga-brca/biospecimen/biotab...,01-data/audit/tcga-brca/variables/biospecimen_...,6315,6,2,3,Primary TSV preserves source line-1 headers ex...
5,20260413T070359Z,20260412T000556Z,biospecimen,biospecimen_sample,c5039e7e-14d8-4e59-ba20-0d3fa38b86df,nationwidechildrens.org_biospecimen_sample_brc...,01-data/raw/tcga-brca/gdc/downloads/biospecime...,biospecimen_sample.tsv,01-data/processed/tcga-brca/biospecimen/biotab...,01-data/audit/tcga-brca/variables/biospecimen_...,2302,27,2,3,Primary TSV preserves source line-1 headers ex...
6,20260413T070359Z,20260412T000556Z,biospecimen,biospecimen_shipment_portion,43569ab9-5a32-45ef-a07e-e93f45416a16,nationwidechildrens.org_biospecimen_shipment_p...,01-data/raw/tcga-brca/gdc/downloads/biospecime...,biospecimen_shipment_portion.tsv,01-data/processed/tcga-brca/biospecimen/biotab...,01-data/audit/tcga-brca/variables/biospecimen_...,1064,12,2,3,Primary TSV preserves source line-1 headers ex...
7,20260413T070359Z,20260412T000556Z,biospecimen,biospecimen_slide,c10090b8-fa42-4e32-86a0-9dedceb5b605,nationwidechildrens.org_biospecimen_slide_brca...,01-data/raw/tcga-brca/gdc/downloads/biospecime...,biospecimen_slide.tsv,01-data/processed/tcga-brca/biospecimen/biotab...,01-data/audit/tcga-brca/variables/biospecimen_...,1995,15,2,3,Primary TSV preserves source line-1 headers ex...

## Table inventory, source-file mapping, and shape checks

In [3]:
parsed_tables = {}
schema_tables = {}
summary_rows = []

for row in manifest_df.to_dict(orient="records"):
    table_path = repo_root / row["output_path"]
    schema_path = repo_root / row["schema_path"]
    table_df = pd.read_csv(table_path, sep="\t", dtype=str, keep_default_na=False, na_filter=False)
    schema_df = pd.read_csv(schema_path, sep="\t", dtype=str, keep_default_na=False, na_filter=False)
    parsed_tables[row["table_name"]] = table_df
    schema_tables[row["table_name"]] = schema_df
    summary_rows.append(
        {
            "parse_run_id": row["parse_run_id"],
            "source_run_id": row["source_run_id"],
            "table_name": row["table_name"],
            "source_filename": row["source_filename"],
            "output_filename": row["output_filename"],
            "row_count": int(len(table_df)),
            "column_count": int(len(table_df.columns)),
            "manifest_row_count": int(row["row_count"]),
            "manifest_column_count": int(row["column_count"]),
            "row_count_matches_manifest": bool(len(table_df) == int(row["row_count"])),
            "column_count_matches_manifest": bool(len(table_df.columns) == int(row["column_count"])),
            "header_preamble_rows": int(row["header_preamble_rows"]),
            "data_start_line": int(row["data_start_line"]),
            "source_path": row["source_path"],
            "output_path": row["output_path"],
            "schema_path": row["schema_path"],
        }
    )

summary_df = pd.DataFrame(summary_rows).sort_values("table_name").reset_index(drop=True)
summary_path = results_root / "37_biospecimen_biotab_table_summary.tsv"
summary_df.to_csv(summary_path, sep="\t", index=False)

print(f"Saved: {summary_path}")
display(summary_df)

Saved: D:\Projects\brcapath-rx\09-trials\01-tcga-only-source-audited\05-results\37_biospecimen_biotab_table_summary.tsv

,parse_run_id,source_run_id,table_name,source_filename,output_filename,row_count,column_count,manifest_row_count,manifest_column_count,row_count_matches_manifest,column_count_matches_manifest,header_preamble_rows,data_start_line,source_path,output_path,schema_path
0,20260413T070359Z,20260412T000556Z,biospecimen_aliquot,nationwidechildrens.org_biospecimen_aliquot_br...,biospecimen_aliquot.tsv,14538,15,14538,15,True,True,2,3,01-data/raw/tcga-brca/gdc/downloads/biospecime...,01-data/processed/tcga-brca/biospecimen/biotab...,01-data/audit/tcga-brca/variables/biospecimen_...
1,20260413T070359Z,20260412T000556Z,biospecimen_analyte,nationwidechildrens.org_biospecimen_analyte_br...,biospecimen_analyte.tsv,6315,17,6315,17,True,True,2,3,01-data/raw/tcga-brca/gdc/downloads/biospecime...,01-data/processed/tcga-brca/biospecimen/biotab...,01-data/audit/tcga-brca/variables/biospecimen_...
2,20260413T070359Z,20260412T000556Z,biospecimen_diagnostic_slides,nationwidechildrens.org_biospecimen_diagnostic...,biospecimen_diagnostic_slides.tsv,1142,4,1142,4,True,True,2,3,01-data/raw/tcga-brca/gdc/downloads/biospecime...,01-data/processed/tcga-brca/biospecimen/biotab...,01-data/audit/tcga-brca/variables/biospecimen_...
3,20260413T070359Z,20260412T000556Z,biospecimen_portion,nationwidechildrens.org_biospecimen_portion_br...,biospecimen_portion.tsv,2310,10,2310,10,True,True,2,3,01-data/raw/tcga-brca/gdc/downloads/biospecime...,01-data/processed/tcga-brca/biospecimen/biotab...,01-data/audit/tcga-brca/variables/biospecimen_...
4,20260413T070359Z,20260412T000556Z,biospecimen_protocol,nationwidechildrens.org_biospecimen_protocol_b...,biospecimen_protocol.tsv,6315,6,6315,6,True,True,2,3,01-data/raw/tcga-brca/gdc/downloads/biospecime...,01-data/processed/tcga-brca/biospecimen/biotab...,01-data/audit/tcga-brca/variables/biospecimen_...
5,20260413T070359Z,20260412T000556Z,biospecimen_sample,nationwidechildrens.org_biospecimen_sample_brc...,biospecimen_sample.tsv,2302,27,2302,27,True,True,2,3,01-data/raw/tcga-brca/gdc/downloads/biospecime...,01-data/processed/tcga-brca/biospecimen/biotab...,01-data/audit/tcga-brca/variables/biospecimen_...
6,20260413T070359Z,20260412T000556Z,biospecimen_shipment_portion,nationwidechildrens.org_biospecimen_shipment_p...,biospecimen_shipment_portion.tsv,1064,12,1064,12,True,True,2,3,01-data/raw/tcga-brca/gdc/downloads/biospecime...,01-data/processed/tcga-brca/biospecimen/biotab...,01-data/audit/tcga-brca/variables/biospecimen_...
7,20260413T070359Z,20260412T000556Z,biospecimen_slide,nationwidechildrens.org_biospecimen_slide_brca...,biospecimen_slide.tsv,1995,15,1995,15,True,True,2,3,01-data/raw/tcga-brca/gdc/downloads/biospecime...,01-data/processed/tcga-brca/biospecimen/biotab...,01-data/audit/tcga-brca/variables/biospecimen_...

## Identifier-like field groups by column name only

This section summarizes column-name groups only. It does not harmonize identifiers or interpret biology.

In [4]:
IDENTIFIER_GROUP_PATTERNS = {
    "patient": ["patient"],
    "sample": ["sample"],
    "portion": ["portion"],
    "analyte": ["analyte"],
    "slide": ["slide"],
    "aliquot": ["aliquot"],
    "barcode": ["barcode"],
    "uuid": ["uuid"],
    "protocol": ["protocol"],
    "shipment": ["shipment"],
}

identifier_group_rows = []
for table_name, table_df in parsed_tables.items():
    column_names = list(table_df.columns)
    lower_names = [name.lower() for name in column_names]
    for identifier_group, patterns in IDENTIFIER_GROUP_PATTERNS.items():
        matched_columns = [
            column_names[index]
            for index, lower_name in enumerate(lower_names)
            if any(pattern in lower_name for pattern in patterns)
        ]
        identifier_group_rows.append(
            {
                "table_name": table_name,
                "identifier_group": identifier_group,
                "matched_column_count": len(matched_columns),
                "matched_columns": json.dumps(matched_columns, ensure_ascii=True),
            }
        )

identifier_group_df = (
    pd.DataFrame(identifier_group_rows)
    .sort_values(["table_name", "identifier_group"])
    .reset_index(drop=True)
)
identifier_group_path = results_root / "38_biospecimen_biotab_identifier_field_groups.tsv"
identifier_group_df.to_csv(identifier_group_path, sep="\t", index=False)

print(f"Saved: {identifier_group_path}")
display(identifier_group_df)

Saved: D:\Projects\brcapath-rx\09-trials\01-tcga-only-source-audited\05-results\38_biospecimen_biotab_identifier_field_groups.tsv

,table_name,identifier_group,matched_column_count,matched_columns
0,biospecimen_aliquot,aliquot,2,"[""bcr_aliquot_barcode"", ""bcr_aliquot_uuid""]"
1,biospecimen_aliquot,analyte,0,[]
2,biospecimen_aliquot,barcode,3,"[""bcr_sample_barcode"", ""bcr_aliquot_barcode"", ..."
3,biospecimen_aliquot,patient,1,"[""bcr_patient_uuid""]"
4,biospecimen_aliquot,portion,0,[]
...,...,...,...,...
75,biospecimen_slide,protocol,0,[]
76,biospecimen_slide,sample,1,"[""bcr_sample_barcode""]"
77,biospecimen_slide,shipment,0,[]
78,biospecimen_slide,slide,2,"[""bcr_slide_barcode"", ""bcr_slide_uuid""]"
79,biospecimen_slide,uuid,2,"[""bcr_patient_uuid"", ""bcr_slide_uuid""]"

## Missingness-like token review

This section counts common placeholder tokens directly from the parsed tables without changing the source values.

In [5]:
MISSING_LIKE_TOKENS = {
    "blank": "",
    "not_available": "[Not Available]",
    "not_applicable": "[Not Applicable]",
    "unknown": "[Unknown]",
    "not_evaluated": "[Not Evaluated]",
    "discrepancy": "[Discrepancy]",
}

missingness_rows = []
for table_name, table_df in parsed_tables.items():
    row_count = len(table_df)
    for column_name in table_df.columns:
        values = table_df[column_name].astype(str)
        token_counts = {label: int((values == token).sum()) for label, token in MISSING_LIKE_TOKENS.items()}
        missing_like_count = sum(token_counts.values())
        non_missing_like_values = values.loc[~values.isin(MISSING_LIKE_TOKENS.values())]
        missingness_rows.append(
            {
                "table_name": table_name,
                "column_name": column_name,
                "row_count": int(row_count),
                "blank_count": token_counts["blank"],
                "not_available_count": token_counts["not_available"],
                "not_applicable_count": token_counts["not_applicable"],
                "unknown_count": token_counts["unknown"],
                "not_evaluated_count": token_counts["not_evaluated"],
                "discrepancy_count": token_counts["discrepancy"],
                "missing_like_count": missing_like_count,
                "missing_like_fraction": float(missing_like_count / row_count) if row_count else 0.0,
                "distinct_non_missing_like_count": int(non_missing_like_values.nunique()),
            }
        )

missingness_df = (
    pd.DataFrame(missingness_rows)
    .sort_values(["table_name", "missing_like_fraction", "column_name"], ascending=[True, False, True])
    .reset_index(drop=True)
)
missingness_path = results_root / "39_biospecimen_biotab_missingness_summary.tsv"
missingness_df.to_csv(missingness_path, sep="\t", index=False)

print(f"Saved: {missingness_path}")
display(missingness_df.head(25))

Saved: D:\Projects\brcapath-rx\09-trials\01-tcga-only-source-audited\05-results\39_biospecimen_biotab_missingness_summary.tsv

,table_name,column_name,row_count,blank_count,not_available_count,not_applicable_count,unknown_count,not_evaluated_count,discrepancy_count,missing_like_count,missing_like_fraction,distinct_non_missing_like_count
0,biospecimen_aliquot,bcr_aliquot_barcode,14538,0,0,0,0,0,0,0,0.000000,14538
1,biospecimen_aliquot,bcr_aliquot_uuid,14538,0,0,0,0,0,0,0,0.000000,14538
2,biospecimen_aliquot,bcr_patient_uuid,14538,0,0,0,0,0,0,0,0.000000,1101
3,biospecimen_aliquot,bcr_sample_barcode,14538,0,0,0,0,0,0,0,0.000000,2300
4,biospecimen_aliquot,biospecimen_barcode_bottom,14538,0,0,0,0,0,0,0,0.000000,14537
5,biospecimen_aliquot,center_id,14538,0,0,0,0,0,0,0,0.000000,9
6,biospecimen_aliquot,concentration,14538,0,0,0,0,0,0,0,0.000000,20
7,biospecimen_aliquot,date_of_shipment,14538,0,0,0,0,0,0,0,0.000000,88
8,biospecimen_aliquot,is_derived_from_ffpe,14538,0,0,0,0,0,0,0,0.000000,2
9,biospecimen_aliquot,plate_column,14538,0,0,0,0,0,0,0,0.000000,12
10,biospecimen_aliquot,plate_id,14538,0,0,0,0,0,0,0,0.000000,345
11,biospecimen_aliquot,plate_row,14538,0,0,0,0,0,0,0,0.000000,8
12,biospecimen_aliquot,quantity,14538,0,0,0,0,0,0,0,0.000000,119
13,biospecimen_aliquot,source_center,14538,0,0,0,0,0,0,0,0.000000,1
14,biospecimen_aliquot,volume,14538,0,0,0,0,0,0,0,0.000000,57
15,biospecimen_analyte,well_number,6315,0,6315,0,0,0,0,6315,1.000000,0
16,biospecimen_analyte,ratio_28s_18s,6315,0,5076,0,0,0,0,5076,0.803800,108
17,biospecimen_analyte,rinvalue,6315,0,5076,0,0,0,0,5076,0.803800,41
18,biospecimen_analyte,a260_a280_ratio,6315,0,3397,0,0,0,0,3397,0.537926,109
19,biospecimen_analyte,concentration,6315,0,2774,0,0,0,0,2774,0.439272,15
20,biospecimen_analyte,spectrophotometer_method,6315,0,2774,0,0,0,0,2774,0.439272,2
21,biospecimen_analyte,subportion_sequence,6315,0,2311,0,0,0,0,2311,0.365954,4
22,biospecimen_analyte,normal_tumor_genotype_match,6315,0,1239,0,0,0,0,1239,0.196200,1
23,biospecimen_analyte,pcr_amplification_successful,6315,0,1239,0,0,0,0,1239,0.196200,1
24,biospecimen_analyte,analyte_type,6315,0,0,0,0,0,0,0,0.000000,4

## Linkage-field review by field names only

This section summarizes likely linkage paths from saved headers only. It does not harmonize identifiers or define a final hierarchy.

In [6]:
ROLE_PATTERNS = {
    "patient_fields": ["patient_barcode", "patient_uuid", "bcr_patient"],
    "sample_fields": ["sample_barcode", "sample_uuid", "bcr_sample"],
    "portion_fields": ["portion_barcode", "portion_uuid", "portion_number", "portion_sequence"],
    "analyte_fields": ["analyte_barcode", "analyte_uuid", "analyte_type", "subportion_sequence"],
    "slide_fields": ["slide_barcode", "slide_uuid", "ffpe_slide_uuid"],
    "aliquot_fields": ["aliquot_barcode", "aliquot_uuid", "biospecimen_barcode_bottom"],
    "protocol_fields": ["protocol"],
    "shipment_fields": ["shipment"],
}


def match_columns(column_names: list[str], patterns: list[str]) -> list[str]:
    matched = []
    for column_name in column_names:
        lower_name = column_name.lower()
        if any(pattern in lower_name for pattern in patterns):
            matched.append(column_name)
    return matched


linkage_rows = []
for row in summary_df.to_dict(orient="records"):
    table_name = row["table_name"]
    column_names = list(parsed_tables[table_name].columns)
    matched = {role: match_columns(column_names, patterns) for role, patterns in ROLE_PATTERNS.items()}

    likely_edges = []
    if matched["patient_fields"] and matched["sample_fields"]:
        likely_edges.append("patient -> sample")
    if matched["sample_fields"] and matched["portion_fields"]:
        likely_edges.append("sample -> portion")
    if matched["sample_fields"] and matched["analyte_fields"]:
        likely_edges.append("sample -> analyte")
    if matched["sample_fields"] and matched["slide_fields"]:
        likely_edges.append("sample -> slide")
    if matched["sample_fields"] and matched["aliquot_fields"]:
        likely_edges.append("sample -> aliquot")
    if matched["analyte_fields"] and matched["protocol_fields"]:
        likely_edges.append("analyte -> protocol")
    if matched["portion_fields"] and matched["shipment_fields"]:
        likely_edges.append("portion -> shipment")
    if matched["aliquot_fields"] and matched["shipment_fields"]:
        likely_edges.append("aliquot -> shipment")

    linkage_rows.append(
        {
            "table_name": table_name,
            "source_filename": row["source_filename"],
            "patient_fields": json.dumps(matched["patient_fields"], ensure_ascii=True),
            "sample_fields": json.dumps(matched["sample_fields"], ensure_ascii=True),
            "portion_fields": json.dumps(matched["portion_fields"], ensure_ascii=True),
            "analyte_fields": json.dumps(matched["analyte_fields"], ensure_ascii=True),
            "slide_fields": json.dumps(matched["slide_fields"], ensure_ascii=True),
            "aliquot_fields": json.dumps(matched["aliquot_fields"], ensure_ascii=True),
            "protocol_fields": json.dumps(matched["protocol_fields"], ensure_ascii=True),
            "shipment_fields": json.dumps(matched["shipment_fields"], ensure_ascii=True),
            "likely_linkage_edges": json.dumps(likely_edges, ensure_ascii=True),
            "linkage_comment": "Field-name-only linkage hints. No identifier harmonization or final hierarchy is performed here.",
        }
    )

linkage_df = pd.DataFrame(linkage_rows).sort_values("table_name").reset_index(drop=True)
linkage_path = results_root / "40_biospecimen_biotab_linkage_fields.tsv"
linkage_df.to_csv(linkage_path, sep="\t", index=False)

print(f"Saved: {linkage_path}")
print("Likely linkage path by field names only: patient -> sample -> portion / analyte / slide / aliquot, plus analyte -> protocol and shipment-linked portion or aliquot fields where present.")
display(linkage_df)

Saved: D:\Projects\brcapath-rx\09-trials\01-tcga-only-source-audited\05-results\40_biospecimen_biotab_linkage_fields.tsv
Likely linkage path by field names only: patient -> sample -> portion / analyte / slide / aliquot, plus analyte -> protocol and shipment-linked portion or aliquot fields where present.

,table_name,source_filename,patient_fields,sample_fields,portion_fields,analyte_fields,slide_fields,aliquot_fields,protocol_fields,shipment_fields,likely_linkage_edges,linkage_comment
0,biospecimen_aliquot,nationwidechildrens.org_biospecimen_aliquot_br...,"[""bcr_patient_uuid""]","[""bcr_sample_barcode""]",[],[],[],"[""bcr_aliquot_barcode"", ""bcr_aliquot_uuid"", ""b...",[],"[""date_of_shipment""]","[""patient -> sample"", ""sample -> aliquot"", ""al...",Field-name-only linkage hints. No identifier h...
1,biospecimen_analyte,nationwidechildrens.org_biospecimen_analyte_br...,"[""bcr_patient_uuid""]","[""bcr_sample_barcode""]","[""subportion_sequence""]","[""bcr_analyte_barcode"", ""bcr_analyte_uuid"", ""a...",[],[],[],[],"[""patient -> sample"", ""sample -> portion"", ""sa...",Field-name-only linkage hints. No identifier h...
2,biospecimen_diagnostic_slides,nationwidechildrens.org_biospecimen_diagnostic...,"[""bcr_patient_uuid"", ""bcr_patient_barcode""]","[""bcr_sample_barcode""]",[],[],"[""ffpe_slide_uuid""]",[],[],[],"[""patient -> sample"", ""sample -> slide""]",Field-name-only linkage hints. No identifier h...
3,biospecimen_portion,nationwidechildrens.org_biospecimen_portion_br...,"[""bcr_patient_uuid""]","[""bcr_sample_barcode""]","[""bcr_portion_barcode"", ""bcr_portion_uuid"", ""p...",[],[],[],[],[],"[""patient -> sample"", ""sample -> portion""]",Field-name-only linkage hints. No identifier h...
4,biospecimen_protocol,nationwidechildrens.org_biospecimen_protocol_b...,"[""bcr_patient_uuid""]","[""bcr_sample_barcode""]",[],"[""bcr_analyte_barcode""]",[],[],"[""experimental_protocol_type"", ""protocol_file_...",[],"[""patient -> sample"", ""sample -> analyte"", ""an...",Field-name-only linkage hints. No identifier h...
5,biospecimen_sample,nationwidechildrens.org_biospecimen_sample_brc...,"[""bcr_patient_uuid""]","[""bcr_sample_barcode"", ""bcr_sample_uuid""]",[],[],[],[],[],[],"[""patient -> sample""]",Field-name-only linkage hints. No identifier h...
6,biospecimen_shipment_portion,nationwidechildrens.org_biospecimen_shipment_p...,"[""bcr_patient_uuid""]","[""bcr_sample_barcode""]","[""bcr_shipment_portion_uuid"", ""portion_number""...",[],[],"[""shipment_portion_bcr_aliquot_barcode""]",[],"[""shipment_portion_bcr_aliquot_barcode"", ""bcr_...","[""patient -> sample"", ""sample -> portion"", ""sa...",Field-name-only linkage hints. No identifier h...
7,biospecimen_slide,nationwidechildrens.org_biospecimen_slide_brca...,"[""bcr_patient_uuid""]","[""bcr_sample_barcode""]",[],[],"[""bcr_slide_barcode"", ""bcr_slide_uuid""]",[],[],[],"[""patient -> sample"", ""sample -> slide""]",Field-name-only linkage hints. No identifier h...

## Preamble and schema summary

This section confirms that the saved schema files carry source line-2 CDE metadata while the primary parsed tables preserve source line-1 headers exactly.

In [7]:
preamble_rows = []
for row in manifest_df.to_dict(orient="records"):
    table_name = row["table_name"]
    schema_df = schema_tables[table_name]
    alternate_values = schema_df["alternate_column_name"].astype(str)
    cde_values = schema_df["cde_id_raw"].astype(str)
    cde_columns = schema_df.loc[cde_values != "", "raw_column_name"].tolist()
    preamble_rows.append(
        {
            "table_name": table_name,
            "source_filename": row["source_filename"],
            "header_preamble_rows": int(row["header_preamble_rows"]),
            "data_start_line": int(row["data_start_line"]),
            "column_count": int(row["column_count"]),
            "schema_row_count": int(len(schema_df)),
            "non_empty_alternate_column_name_count": int((alternate_values != "").sum()),
            "non_empty_cde_id_count": int((cde_values != "").sum()),
            "cde_id_columns": json.dumps(cde_columns, ensure_ascii=True),
            "parse_notes": row["parse_notes"],
        }
    )

preamble_df = pd.DataFrame(preamble_rows).sort_values("table_name").reset_index(drop=True)
preamble_path = results_root / "41_biospecimen_biotab_preamble_summary.tsv"
preamble_df.to_csv(preamble_path, sep="\t", index=False)

print(f"Saved: {preamble_path}")
display(preamble_df)

Saved: D:\Projects\brcapath-rx\09-trials\01-tcga-only-source-audited\05-results\41_biospecimen_biotab_preamble_summary.tsv

,table_name,source_filename,header_preamble_rows,data_start_line,column_count,schema_row_count,non_empty_alternate_column_name_count,non_empty_cde_id_count,cde_id_columns,parse_notes
0,biospecimen_aliquot,nationwidechildrens.org_biospecimen_aliquot_br...,2,3,15,15,0,1,"[""is_derived_from_ffpe""]",Primary TSV preserves source line-1 headers ex...
1,biospecimen_analyte,nationwidechildrens.org_biospecimen_analyte_br...,2,3,17,17,0,1,"[""is_derived_from_ffpe""]",Primary TSV preserves source line-1 headers ex...
2,biospecimen_diagnostic_slides,nationwidechildrens.org_biospecimen_diagnostic...,2,3,4,4,0,1,"[""bcr_patient_barcode""]",Primary TSV preserves source line-1 headers ex...
3,biospecimen_portion,nationwidechildrens.org_biospecimen_portion_br...,2,3,10,10,0,2,"[""LCE"", ""is_ffpe""]",Primary TSV preserves source line-1 headers ex...
4,biospecimen_protocol,nationwidechildrens.org_biospecimen_protocol_b...,2,3,6,6,0,0,[],Primary TSV preserves source line-1 headers ex...
5,biospecimen_sample,nationwidechildrens.org_biospecimen_sample_brc...,2,3,27,27,0,4,"[""days_to_sample_procurement"", ""is_ffpe"", ""met...",Primary TSV preserves source line-1 headers ex...
6,biospecimen_shipment_portion,nationwidechildrens.org_biospecimen_shipment_p...,2,3,12,12,0,1,"[""is_ffpe""]",Primary TSV preserves source line-1 headers ex...
7,biospecimen_slide,nationwidechildrens.org_biospecimen_slide_brca...,2,3,15,15,0,3,"[""is_derived_from_ffpe"", ""percent_necrosis"", ""...",Primary TSV preserves source line-1 headers ex...

## Review reminder

These outputs stay at the source-audit layer. They do not define a final cohort, freeze an endpoint, parse XML, or create a modeling-ready biospecimen hierarchy.