# TCGA-BRCA Cohort Blueprint Review

This notebook is review-only. It loads the latest saved cohort blueprint outputs from disk, checks the run-level validation state, and writes review tables for human source audit and study-design review.

## Load the latest saved cohort blueprint run

In [1]:
from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
from IPython.display import display


def find_repo_root(start: Path) -> Path:
    for candidate in [start, *start.parents]:
        if (candidate / '.git').exists():
            return candidate
    raise FileNotFoundError('Could not locate the repository root from the current working directory.')


repo_root = find_repo_root(Path.cwd())
latest_pointer_path = (
    repo_root
    / '01-data'
    / 'audit'
    / 'tcga-brca'
    / 'cohort'
    / 'tcga_brca_cohort_blueprint_latest.json'
)
if not latest_pointer_path.exists():
    raise FileNotFoundError(
        f'Latest cohort blueprint pointer not found: {latest_pointer_path}. Run the cohort blueprint script first.'
    )

latest_pointer = json.loads(latest_pointer_path.read_text(encoding='utf-8'))
required_path = repo_root / latest_pointer['cohort_blueprint_required_fields_tsv']
optional_path = repo_root / latest_pointer['cohort_blueprint_optional_fields_tsv']
deferred_path = repo_root / latest_pointer['cohort_blueprint_deferred_fields_tsv']
join_path_path = repo_root / latest_pointer['cohort_blueprint_join_path_tsv']
ambiguities_path = repo_root / latest_pointer['cohort_blueprint_ambiguities_tsv']
summary_path = repo_root / latest_pointer['cohort_blueprint_summary_tsv']
run_log_path = repo_root / latest_pointer['run_log_json']
results_root = repo_root / '09-trials' / '01-tcga-only-source-audited' / '05-results'
results_root.mkdir(parents=True, exist_ok=True)

display(pd.DataFrame([latest_pointer]))

,updated_at_utc,blueprint_run_id,shortlist_run_id,core_audit_run_id,clinical_parse_run_id,endpoint_crosswalk_run_id,biospecimen_crosswalk_run_id,biospecimen_parse_run_id,clinical_source_run_id,biospecimen_source_run_id,...,cohort_blueprint_required_fields_tsv,cohort_blueprint_optional_fields_tsv,cohort_blueprint_deferred_fields_tsv,cohort_blueprint_join_path_tsv,cohort_blueprint_ambiguities_tsv,cohort_blueprint_summary_tsv,run_log_json,clinical_shortlist_latest_json,endpoint_crosswalk_latest_json,biospecimen_crosswalk_latest_json
0,2026-04-13T08:18:35Z,20260413T081835Z,20260412T033602Z,20260412T023839Z,20260412T010932Z,20260412T042036Z,20260413T073640Z,20260413T070359Z,20260412T000556Z,20260412T000556Z,...,01-data/audit/tcga-brca/cohort/cohort_blueprin...,01-data/audit/tcga-brca/cohort/cohort_blueprin...,01-data/audit/tcga-brca/cohort/cohort_blueprin...,01-data/audit/tcga-brca/cohort/cohort_blueprin...,01-data/audit/tcga-brca/cohort/cohort_blueprin...,01-data/audit/tcga-brca/cohort/cohort_blueprin...,01-data/audit/tcga-brca/cohort/cohort_blueprin...,01-data/audit/tcga-brca/variables/tcga_brca_cl...,01-data/audit/tcga-brca/variables/tcga_brca_en...,01-data/audit/tcga-brca/variables/tcga_brca_bi...

## Load saved cohort blueprint artifacts

In [2]:
required_df = pd.read_csv(required_path, sep='\t')
optional_df = pd.read_csv(optional_path, sep='\t')
deferred_df = pd.read_csv(deferred_path, sep='\t')
join_path_df = pd.read_csv(join_path_path, sep='\t')
ambiguity_df = pd.read_csv(ambiguities_path, sep='\t')
summary_df = pd.read_csv(summary_path, sep='\t')
run_log = json.loads(run_log_path.read_text(encoding='utf-8'))

field_bucket_order = [
    'required_for_first_baseline',
    'optional_for_first_baseline',
    'deferred_for_later_expansion',
]
source_layer_order = ['clinical', 'endpoint', 'biospecimen']
join_strength_order = ['strong_current_evidence', 'workable_but_needs_review', 'deferred']
link_timing_order = ['link_now', 'link_later', 'prepare_only']
severity_order = ['high', 'medium', 'low']

for frame in [required_df, optional_df, deferred_df]:
    frame['field_bucket'] = pd.Categorical(frame['field_bucket'], categories=field_bucket_order, ordered=True)
    frame['source_layer'] = pd.Categorical(frame['source_layer'], categories=source_layer_order, ordered=True)

join_path_df['join_strength'] = pd.Categorical(
    join_path_df['join_strength'], categories=join_strength_order, ordered=True
)
join_path_df['link_timing'] = pd.Categorical(
    join_path_df['link_timing'], categories=link_timing_order, ordered=True
)
ambiguity_df['severity'] = pd.Categorical(
    ambiguity_df['severity'], categories=severity_order, ordered=True
)

unit_rows = summary_df.loc[
    summary_df['summary_metric'].isin(['proposed_unit_of_analysis', 'proposed_biospecimen_anchor'])
].reset_index(drop=True)
strong_join_df = join_path_df.loc[
    join_path_df['join_strength'] == 'strong_current_evidence'
].reset_index(drop=True)
blocking_ambiguity_df = ambiguity_df.loc[
    ambiguity_df['blocks_final_cohort_construction'] == True
].sort_values(['severity', 'ambiguity_id']).reset_index(drop=True)

print(f'Required fields TSV: {required_path}')
print(f'Optional fields TSV: {optional_path}')
print(f'Deferred fields TSV: {deferred_path}')
print(f'Join path TSV: {join_path_path}')
print(f'Ambiguities TSV: {ambiguities_path}')
print(f'Summary TSV: {summary_path}')
print(f'Run log: {run_log_path}')
print(f"Blueprint run ID: {latest_pointer['blueprint_run_id']}")
display(pd.DataFrame([run_log['validation']]))
display(unit_rows)
display(strong_join_df)
display(blocking_ambiguity_df)

Required fields TSV: D:\Projects\brcapath-rx\01-data\audit\tcga-brca\cohort\cohort_blueprint_runs\20260413T081835Z\cohort_blueprint_required_fields.tsv
Optional fields TSV: D:\Projects\brcapath-rx\01-data\audit\tcga-brca\cohort\cohort_blueprint_runs\20260413T081835Z\cohort_blueprint_optional_fields.tsv
Deferred fields TSV: D:\Projects\brcapath-rx\01-data\audit\tcga-brca\cohort\cohort_blueprint_runs\20260413T081835Z\cohort_blueprint_deferred_fields.tsv
Join path TSV: D:\Projects\brcapath-rx\01-data\audit\tcga-brca\cohort\cohort_blueprint_runs\20260413T081835Z\cohort_blueprint_join_path.tsv
Ambiguities TSV: D:\Projects\brcapath-rx\01-data\audit\tcga-brca\cohort\cohort_blueprint_runs\20260413T081835Z\cohort_blueprint_ambiguities.tsv
Summary TSV: D:\Projects\brcapath-rx\01-data\audit\tcga-brca\cohort\cohort_blueprint_runs\20260413T081835Z\cohort_blueprint_summary.tsv
Run log: D:\Projects\brcapath-rx\01-data\audit\tcga-brca\cohort\cohort_blueprint_runs\20260413T081835Z\run_log.json
Blueprint run ID: 20260413T081835Z

,passed,clinical_shortlist_latest_pointer_found,endpoint_crosswalk_latest_pointer_found,biospecimen_crosswalk_latest_pointer_found,clinical_shortlist_run_log_completed,clinical_core_audit_run_log_completed,clinical_biotab_run_log_completed,source_run_log_completed,endpoint_crosswalk_run_log_completed,biospecimen_crosswalk_run_log_completed,...,optional_fields_row_count_positive,deferred_fields_row_count_positive,join_path_row_count_positive,ambiguities_row_count_positive,summary_row_count_positive,field_assignment_disjoint,join_strength_values_valid,ambiguity_severity_values_valid,no_prior_run_overwrite,latest_pointer_written_after_success_only
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

,blueprint_run_id,summary_section,summary_metric,summary_value,notes
0,20260413T081835Z,design,proposed_unit_of_analysis,patient/case,The first baseline blueprint keeps the analysi...
1,20260413T081835Z,design,proposed_biospecimen_anchor,sample,biospecimen_sample is the required specimen an...

,blueprint_run_id,step_order,left_node,right_node,left_table_name,right_table_name,left_field_name,right_field_name,join_keys_or_evidence,join_strength,link_timing,rationale,ambiguity_flag,notes_placeholder
0,20260413T081835Z,1,patient/case,clinical_patient,NaN,clinical_patient,case_identifier,bcr_patient_barcode / bcr_patient_uuid,clinical_patient carries both audited case ide...,strong_current_evidence,link_now,Use clinical_patient as the central case-level...,False,[fill in during cohort blueprint review]
1,20260413T081835Z,4,patient/case,clinical_patient endpoint-like fields,clinical_patient,clinical_patient,bcr_patient_barcode / bcr_patient_uuid,vital_status / last_contact_days_to / tumor_st...,clinical_patient endpoint-like fields already ...,strong_current_evidence,prepare_only,Patient-table endpoint candidates can be carri...,False,[fill in during cohort blueprint review]
2,20260413T081835Z,7,sample,portion,biospecimen_sample,biospecimen_portion,bcr_sample_barcode / bcr_sample_uuid,bcr_sample_barcode / bcr_portion_barcode / bcr...,biospecimen_portion repeats bcr_sample_barcode...,strong_current_evidence,link_later,Sample-to-portion is the strongest saved child...,False,[fill in during cohort blueprint review]

,blueprint_run_id,ambiguity_id,ambiguity_category,source_layer,table_name,field_name_or_step,severity,why_unresolved,current_saved_evidence,proposed_blueprint_handling,blocks_final_cohort_construction,notes_placeholder
0,20260413T081835Z,A01,endpoint_overlap_patient_vs_followup,endpoint,clinical_patient | clinical_follow_up_v4_0,vital_status,high,The same endpoint-like field exists in both pa...,clinical_patient.vital_status has 1097 non-mis...,Carry both rows as endpoint join-preparation f...,True,[fill in during cohort blueprint review]
1,20260413T081835Z,A02,endpoint_overlap_patient_vs_followup,endpoint,clinical_patient | clinical_follow_up_v4_0,last_contact_days_to,high,Patient and follow-up tables both carry last-c...,clinical_patient.last_contact_days_to has 993 ...,Keep both rows optional and endpoint-preparato...,True,[fill in during cohort blueprint review]
2,20260413T081835Z,A03,endpoint_overlap_patient_vs_followup,endpoint,clinical_patient | clinical_follow_up_v4_0,tumor_status,high,Tumor-status signals overlap across patient an...,clinical_patient.tumor_status has 972 non-miss...,Preserve both rows for later endpoint review a...,True,[fill in during cohort blueprint review]
3,20260413T081835Z,A04,endpoint_overlap_patient_vs_followup,endpoint,clinical_patient | clinical_follow_up_v4_0,new_tumor_event_dx_indicator,high,New-tumor-event indicators overlap across pati...,clinical_patient.new_tumor_event_dx_indicator ...,Keep both rows as later endpoint-reconciliatio...,True,[fill in during cohort blueprint review]
4,20260413T081835Z,A05,sparse_endpoint_timing,endpoint,clinical_patient | clinical_follow_up_v4_0,death_days_to,high,Death timing exists in both tables but remains...,clinical_patient.death_days_to has 104 non-mis...,Record death timing as deferred endpoint evide...,True,[fill in during cohort blueprint review]
5,20260413T081835Z,A06,all_missing_progression_timing,endpoint,clinical_patient,days_to_patient_progression_free | days_to_tum...,high,Progression timing fields were surfaced only a...,Both progression timing fields have 0 non-miss...,Keep both fields deferred and exclude them fro...,True,[fill in during cohort blueprint review]
6,20260413T081835Z,A07,clinical_vs_biospecimen_patient_identifiers,clinical | biospecimen,clinical_patient | biospecimen_sample | biospe...,bcr_patient_barcode | bcr_patient_uuid,high,Clinical and biospecimen layers expose both pa...,clinical_patient has 1097 non-missing values f...,Use both identifier forms as evidence-bearing ...,True,[fill in during cohort blueprint review]
7,20260413T081835Z,A08,case_count_mismatch,clinical | source | biospecimen,clinical_patient | source_metadata | biospecim...,case coverage counts,high,"The saved clinical, source-acquisition, and bi...",clinical_patient row count is 1097; clinical s...,Flag cross-layer case counts as a blocking rec...,True,[fill in during cohort blueprint review]

## Save required blueprint review table

In [3]:
field_review_columns = [
    'field_bucket',
    'source_layer',
    'table_name',
    'field_name',
    'proposed_role',
    'rationale',
    'dependency_for_join',
    'ambiguity_flag',
    'upstream_source_type',
    'upstream_bucket_or_role',
    'upstream_rule',
    'manual_review_priority',
    'missing_like_fraction',
    'non_missing_count',
    'distinct_non_missing_count',
    'paired_field_name',
    'evidence_rule',
    'evidence_rate',
    'notes_placeholder',
]

required_review_df = (
    required_df.loc[:, field_review_columns]
    .sort_values(['source_layer', 'table_name', 'field_name'], ascending=[True, True, True])
    .reset_index(drop=True)
)
required_review_path = results_root / '48_cohort_blueprint_required_fields.tsv'
required_review_df.to_csv(required_review_path, sep='\t', index=False)

print(f'Saved: {required_review_path}')
display(required_review_df)

Saved: D:\Projects\brcapath-rx\09-trials\01-tcga-only-source-audited\05-results\48_cohort_blueprint_required_fields.tsv

,field_bucket,source_layer,table_name,field_name,proposed_role,rationale,dependency_for_join,ambiguity_flag,upstream_source_type,upstream_bucket_or_role,upstream_rule,manual_review_priority,missing_like_fraction,non_missing_count,distinct_non_missing_count,paired_field_name,evidence_rule,evidence_rate,notes_placeholder
0,required_for_first_baseline,clinical,clinical_patient,age_at_diagnosis,baseline_covariate,Carry forward audited usable baseline fields a...,case_level_baseline_core,False,clinical_shortlist,usable_baseline,baseline_candidate_structured_core_field,low,0.000000,1097,65,NaN,NaN,NaN,[fill in during cohort blueprint review]
1,required_for_first_baseline,clinical,clinical_patient,ajcc_metastasis_pathologic_pm,baseline_covariate,Carry forward audited usable baseline fields a...,case_level_baseline_core,False,clinical_shortlist,usable_baseline,baseline_candidate_structured_core_field,low,0.000000,1097,4,NaN,NaN,NaN,[fill in during cohort blueprint review]
2,required_for_first_baseline,clinical,clinical_patient,ajcc_nodes_pathologic_pn,baseline_covariate,Carry forward audited usable baseline fields a...,case_level_baseline_core,False,clinical_shortlist,usable_baseline,baseline_candidate_structured_core_field,low,0.000000,1097,16,NaN,NaN,NaN,[fill in during cohort blueprint review]
3,required_for_first_baseline,clinical,clinical_patient,ajcc_pathologic_tumor_stage,baseline_covariate,Carry forward audited usable baseline fields a...,case_level_baseline_core,False,clinical_shortlist,usable_baseline,baseline_candidate_structured_core_field,low,0.010027,1086,12,NaN,NaN,NaN,[fill in during cohort blueprint review]
4,required_for_first_baseline,clinical,clinical_patient,ajcc_staging_edition,baseline_covariate,Carry forward audited usable baseline fields a...,case_level_baseline_core,False,clinical_shortlist,usable_baseline,baseline_candidate_structured_core_field,medium,0.128532,956,5,NaN,NaN,NaN,[fill in during cohort blueprint review]
5,required_for_first_baseline,clinical,clinical_patient,ajcc_tumor_pathologic_pt,baseline_covariate,Carry forward audited usable baseline fields a...,case_level_baseline_core,False,clinical_shortlist,usable_baseline,baseline_candidate_structured_core_field,low,0.000000,1097,13,NaN,NaN,NaN,[fill in during cohort blueprint review]
6,required_for_first_baseline,clinical,clinical_patient,anatomic_neoplasm_subdivision,baseline_covariate,Carry forward audited usable baseline fields a...,case_level_baseline_core,False,clinical_shortlist,usable_baseline,baseline_candidate_structured_core_field,low,0.000000,1097,53,NaN,NaN,NaN,[fill in during cohort blueprint review]
7,required_for_first_baseline,clinical,clinical_patient,axillary_staging_method,baseline_covariate,Carry forward audited usable baseline fields a...,case_level_baseline_core,False,clinical_shortlist,usable_baseline,baseline_candidate_structured_core_field,medium,0.196901,881,5,NaN,NaN,NaN,[fill in during cohort blueprint review]
8,required_for_first_baseline,clinical,clinical_patient,bcr_patient_barcode,case_join_identifier,Retain both audited clinical patient identifie...,case_to_clinical_and_case_to_followup_preparation,False,clinical_core_field_audit,manual_blueprint_backbone,cohort_blueprint_required_case_identifier,NaN,0.000000,1097,1097,NaN,NaN,NaN,[fill in during cohort blueprint review]
9,required_for_first_baseline,clinical,clinical_patient,bcr_patient_uuid,case_join_identifier,Retain both audited clinical patient identifie...,case_to_clinical_and_case_to_followup_preparation,False,clinical_core_field_audit,manual_blueprint_backbone,cohort_blueprint_required_case_identifier,NaN,0.000000,1097,1097,NaN,NaN,NaN,[fill in during cohort blueprint review]
10,required_for_first_baseline,clinical,clinical_patient,birth_days_to,baseline_covariate,Carry forward audited usable baseline fields a...,case_level_baseline_core,False,clinical_shortlist,usable_baseline,baseline_candidate_structured_core_field,low,0.013674,1082,1045,NaN,NaN,NaN,[fill in during cohort blueprint review]
11,required_for_first_baseline,clinical,clinical_patient,er_status_by_ihc,baseline_covariate,Carry forward audited usable baseline fields a...,case_level_baseline_core,False,clinical_shortlist,usable_baseline,baseline_candidate_structured_core_field,low,0.044667,1048,3,NaN,NaN,NaN,[fill in during cohort blueprint review]
12,required_for_first_baseline,clinical,clinical_patient,ethnicity,baseline_covariate,Carry forward audited usable baseline fields a...,case_level_baseline_core,False,clinical_shortlist,usable_baseline,baseline_candidate_structured_core_field,medium,0.158614,923,2,NaN,NaN,NaN,[fill in during cohort blueprint review]
13,required_for_first_baseline,clinical,clinical_patient,gender,baseline_covariate,Carry forward audited usable baseline fields a...,case_level_baseline_core,False,clinical_shortlist,usable_baseline,baseline_candidate_structured_core_field,low,0.000000,1097,2,NaN,NaN,NaN,[fill in during cohort blueprint review]
14,required_for_first_baseline,clinical,clinical_patient,her2_status_by_ihc,baseline_covariate,Carry forward audited usable baseline fields a...,case_level_baseline_core,False,clinical_shortlist,usable_baseline,baseline_candidate_structured_core_field,medium,0.162261,919,4,NaN,NaN,NaN,[fill in during cohort blueprint review]
15,required_for_first_baseline,clinical,clinical_patient,histological_type,baseline_covariate,Carry forward audited usable baseline fields a...,case_level_baseline_core,False,clinical_shortlist,usable_baseline,baseline_candidate_structured_core_field,low,0.000912,1096,8,NaN,NaN,NaN,[fill in during cohort blueprint review]
16,required_for_first_baseline,clinical,clinical_patient,history_other_malignancy,baseline_covariate,Carry forward audited usable baseline fields a...,case_level_baseline_core,False,clinical_shortlist,usable_baseline,baseline_candidate_structured_core_field,low,0.000912,1096,2,NaN,NaN,NaN,[fill in during cohort blueprint review]
17,required_for_first_baseline,clinical,clinical_patient,icd_10,baseline_covariate,Carry forward audited usable baseline fields a...,case_level_baseline_core,False,clinical_shortlist,usable_baseline,baseline_candidate_structured_core_field,low,0.000000,1097,7,NaN,NaN,NaN,[fill in during cohort blueprint review]
18,required_for_first_baseline,clinical,clinical_patient,icd_o_3_histology,baseline_covariate,Carry forward audited usable baseline fields a...,case_level_baseline_core,False,clinical_shortlist,usable_baseline,baseline_candidate_structured_core_field,low,0.000000,1097,22,NaN,NaN,NaN,[fill in during cohort blueprint review]
19,required_for_first_baseline,clinical,clinical_patient,icd_o_3_site,baseline_covariate,Carry forward audited usable baseline fields a...,case_level_baseline_core,False,clinical_shortlist,usable_baseline,baseline_candidate_structured_core_field,low,0.000000,1097,6,NaN,NaN,NaN,[fill in during cohort blueprint review]
20,required_for_first_baseline,clinical,clinical_patient,initial_pathologic_dx_year,baseline_covariate,Carry forward audited usable baseline fields a...,case_level_baseline_core,False,clinical_shortlist,usable_baseline,baseline_candidate_structured_core_field,low,0.001823,1095,26,NaN,NaN,NaN,[fill in during cohort blueprint review]
21,required_for_first_baseline,clinical,clinical_patient,lymph_nodes_examined_count,baseline_covariate,Carry forward audited usable baseline fields a...,case_level_baseline_core,False,clinical_shortlist,usable_baseline,baseline_candidate_structured_core_field,medium,0.114859,971,42,NaN,NaN,NaN,[fill in during cohort blueprint review]
22,required_for_first_baseline,clinical,clinical_patient,lymph_nodes_examined_he_count,baseline_covariate,Carry forward audited usable baseline fields a...,case_level_baseline_core,False,clinical_shortlist,usable_baseline,baseline_candidate_structured_core_field,medium,0.153145,929,31,NaN,NaN,NaN,[fill in during cohort blueprint review]
23,required_for_first_baseline,clinical,clinical_patient,margin_status,baseline_covariate,Carry forward audited usable baseline fields a...,case_level_baseline_core,False,clinical_shortlist,usable_baseline,baseline_candidate_structured_core_field,low,0.061987,1029,3,NaN,NaN,NaN,[fill in during cohort blueprint review]
24,required_for_first_baseline,clinical,clinical_patient,menopause_status,baseline_covariate,Carry forward audited usable baseline fields a...,case_level_baseline_core,False,clinical_shortlist,usable_baseline,baseline_candidate_structured_core_field,low,0.082042,1007,4,NaN,NaN,NaN,[fill in during cohort blueprint review]
25,required_for_first_baseline,clinical,clinical_patient,method_initial_path_dx,baseline_covariate,Carry forward audited usable baseline fields a...,case_level_baseline_core,False,clinical_shortlist,usable_baseline,baseline_candidate_structured_core_field,low,0.089335,999,7,NaN,NaN,NaN,[fill in during cohort blueprint review]
26,required_for_first_baseline,clinical,clinical_patient,pr_status_by_ihc,baseline_covariate,Carry forward audited usable baseline fields a...,case_level_baseline_core,False,clinical_shortlist,usable_baseline,baseline_candidate_structured_core_field,low,0.045579,1047,3,NaN,NaN,NaN,[fill in during cohort blueprint review]
27,required_for_first_baseline,clinical,clinical_patient,race,baseline_covariate,Carry forward audited usable baseline fields a...,case_level_baseline_core,False,clinical_shortlist,usable_baseline,baseline_candidate_structured_core_field,low,0.086600,1002,4,NaN,NaN,NaN,[fill in during cohort blueprint review]
28,required_for_first_baseline,clinical,clinical_patient,surgical_procedure_first,baseline_covariate,Carry forward audited usable baseline fields a...,case_level_baseline_core,False,clinical_shortlist,usable_baseline,baseline_candidate_structured_core_field,low,0.050137,1042,4,NaN,NaN,NaN,[fill in during cohort blueprint review]
29,required_for_first_baseline,biospecimen,biospecimen_sample,bcr_patient_uuid,biospecimen_sample_anchor,Use the audited biospecimen sample identifiers...,case_to_sample_anchor,False,biospecimen_identifier_crosswalk,primary_link_candidate,role_primary_patient_best_uuid_candidate,low,0.000000,2302,1101,bcr_sample_barcode,same_row_copresence_only,1.0,[fill in during cohort blueprint review]
30,required_for_first_baseline,biospecimen,biospecimen_sample,bcr_sample_barcode,biospecimen_sample_anchor,Use the audited biospecimen sample identifiers...,case_to_sample_anchor,False,biospecimen_identifier_crosswalk,primary_link_candidate,role_primary_canonical_level_identifier,low,0.000000,2302,2302,bcr_sample_uuid,exact_pair_one_to_one_same_table,1.0,[fill in during cohort blueprint review]
31,required_for_first_baseline,biospecimen,biospecimen_sample,bcr_sample_uuid,biospecimen_sample_anchor,Use the audited biospecimen sample identifiers...,case_to_sample_anchor,False,biospecimen_identifier_crosswalk,primary_link_candidate,role_primary_canonical_level_identifier,low,0.000000,2302,2302,bcr_sample_barcode,exact_pair_one_to_one_same_table,1.0,[fill in during cohort blueprint review]

## Save optional and deferred blueprint review tables

In [4]:
optional_review_df = (
    optional_df.loc[:, field_review_columns]
    .sort_values(['source_layer', 'table_name', 'field_name'], ascending=[True, True, True])
    .reset_index(drop=True)
)
optional_review_path = results_root / '49_cohort_blueprint_optional_fields.tsv'
optional_review_df.to_csv(optional_review_path, sep='\t', index=False)

deferred_review_df = (
    deferred_df.loc[:, field_review_columns]
    .sort_values(['source_layer', 'table_name', 'field_name'], ascending=[True, True, True])
    .reset_index(drop=True)
)
deferred_review_path = results_root / '50_cohort_blueprint_deferred_fields.tsv'
deferred_review_df.to_csv(deferred_review_path, sep='\t', index=False)

print(f'Saved: {optional_review_path}')
print(f'Saved: {deferred_review_path}')
display(optional_review_df)
display(deferred_review_df)

Saved: D:\Projects\brcapath-rx\09-trials\01-tcga-only-source-audited\05-results\49_cohort_blueprint_optional_fields.tsv
Saved: D:\Projects\brcapath-rx\09-trials\01-tcga-only-source-audited\05-results\50_cohort_blueprint_deferred_fields.tsv

,field_bucket,source_layer,table_name,field_name,proposed_role,rationale,dependency_for_join,ambiguity_flag,upstream_source_type,upstream_bucket_or_role,upstream_rule,manual_review_priority,missing_like_fraction,non_missing_count,distinct_non_missing_count,paired_field_name,evidence_rule,evidence_rate,notes_placeholder
0,optional_for_first_baseline,clinical,clinical_drug,bcr_patient_barcode,case_join_identifier,Keep the audited patient and follow-up identif...,case_to_treatment_optional_link,False,clinical_core_field_audit,manual_blueprint_join_support,cohort_blueprint_optional_join_identifier,NaN,0.000000,2406,780,NaN,NaN,NaN,[fill in during cohort blueprint review]
1,optional_for_first_baseline,clinical,clinical_drug,bcr_patient_uuid,case_join_identifier,Keep the audited patient and follow-up identif...,case_to_treatment_optional_link,False,clinical_core_field_audit,manual_blueprint_join_support,cohort_blueprint_optional_join_identifier,NaN,0.000000,2406,780,NaN,NaN,NaN,[fill in during cohort blueprint review]
2,optional_for_first_baseline,clinical,clinical_drug,pharmaceutical_therapy_drug_name,treatment_proxy_field,Preserve audited treatment-proxy fields as opt...,optional_case_level_treatment_proxy,True,clinical_shortlist,usable_treatment_proxy,treatment_proxy_direct_treatment_table,medium,0.006650,2390,203,NaN,NaN,NaN,[fill in during cohort blueprint review]
3,optional_for_first_baseline,clinical,clinical_drug,pharmaceutical_therapy_type,treatment_proxy_field,Preserve audited treatment-proxy fields as opt...,optional_case_level_treatment_proxy,True,clinical_shortlist,usable_treatment_proxy,treatment_proxy_direct_treatment_table,medium,0.002909,2399,8,NaN,NaN,NaN,[fill in during cohort blueprint review]
4,optional_for_first_baseline,clinical,clinical_drug,pharmaceutical_tx_ended_days_to,treatment_proxy_field,Preserve audited treatment-proxy fields as opt...,optional_case_level_treatment_proxy,True,clinical_shortlist,usable_treatment_proxy,treatment_proxy_direct_treatment_table,medium,0.249792,1805,504,NaN,NaN,NaN,[fill in during cohort blueprint review]
5,optional_for_first_baseline,clinical,clinical_drug,pharmaceutical_tx_ongoing_indicator,treatment_proxy_field,Preserve audited treatment-proxy fields as opt...,optional_case_level_treatment_proxy,True,clinical_shortlist,usable_treatment_proxy,treatment_proxy_direct_treatment_table,medium,0.006234,2391,2,NaN,NaN,NaN,[fill in during cohort blueprint review]
6,optional_for_first_baseline,clinical,clinical_drug,pharmaceutical_tx_started_days_to,treatment_proxy_field,Preserve audited treatment-proxy fields as opt...,optional_case_level_treatment_proxy,True,clinical_shortlist,usable_treatment_proxy,treatment_proxy_direct_treatment_table,medium,0.049044,2288,486,NaN,NaN,NaN,[fill in during cohort blueprint review]
7,optional_for_first_baseline,clinical,clinical_follow_up_v4_0,bcr_followup_barcode,followup_join_identifier,Keep the audited patient and follow-up identif...,case_to_followup_or_case_to_treatment_optional...,True,clinical_core_field_audit,manual_blueprint_join_support,cohort_blueprint_optional_join_identifier,NaN,0.000000,716,716,NaN,NaN,NaN,[fill in during cohort blueprint review]
8,optional_for_first_baseline,clinical,clinical_follow_up_v4_0,bcr_followup_uuid,followup_join_identifier,Keep the audited patient and follow-up identif...,case_to_followup_or_case_to_treatment_optional...,True,clinical_core_field_audit,manual_blueprint_join_support,cohort_blueprint_optional_join_identifier,NaN,0.000000,716,716,NaN,NaN,NaN,[fill in during cohort blueprint review]
9,optional_for_first_baseline,clinical,clinical_follow_up_v4_0,bcr_patient_barcode,followup_join_identifier,Keep the audited patient and follow-up identif...,case_to_followup_or_case_to_treatment_optional...,True,clinical_core_field_audit,manual_blueprint_join_support,cohort_blueprint_optional_join_identifier,NaN,0.000000,716,619,NaN,NaN,NaN,[fill in during cohort blueprint review]
10,optional_for_first_baseline,clinical,clinical_follow_up_v4_0,bcr_patient_uuid,followup_join_identifier,Keep the audited patient and follow-up identif...,case_to_followup_or_case_to_treatment_optional...,True,clinical_core_field_audit,manual_blueprint_join_support,cohort_blueprint_optional_join_identifier,NaN,0.000000,716,619,NaN,NaN,NaN,[fill in during cohort blueprint review]
11,optional_for_first_baseline,clinical,clinical_follow_up_v4_0,pharmaceutical_tx_adjuvant,treatment_proxy_field,Preserve audited treatment-proxy fields as opt...,optional_case_level_treatment_proxy,True,clinical_shortlist,usable_treatment_proxy,treatment_proxy_treatment_signal,medium,0.051676,679,2,NaN,NaN,NaN,[fill in during cohort blueprint review]
12,optional_for_first_baseline,clinical,clinical_follow_up_v4_0,radiation_treatment_adjuvant,treatment_proxy_field,Preserve audited treatment-proxy fields as opt...,optional_case_level_treatment_proxy,True,clinical_shortlist,usable_treatment_proxy,treatment_proxy_treatment_signal,medium,0.033520,692,2,NaN,NaN,NaN,[fill in during cohort blueprint review]
13,optional_for_first_baseline,clinical,clinical_patient,history_neoadjuvant_treatment,treatment_proxy_field,Preserve audited treatment-proxy fields as opt...,optional_case_level_treatment_proxy,True,clinical_shortlist,usable_treatment_proxy,treatment_proxy_treatment_signal,medium,0.001823,1095,2,NaN,NaN,NaN,[fill in during cohort blueprint review]
14,optional_for_first_baseline,clinical,clinical_radiation,bcr_patient_barcode,case_join_identifier,Keep the audited patient and follow-up identif...,case_to_treatment_optional_link,False,clinical_core_field_audit,manual_blueprint_join_support,cohort_blueprint_optional_join_identifier,NaN,0.000000,618,528,NaN,NaN,NaN,[fill in during cohort blueprint review]
15,optional_for_first_baseline,clinical,clinical_radiation,bcr_patient_uuid,case_join_identifier,Keep the audited patient and follow-up identif...,case_to_treatment_optional_link,False,clinical_core_field_audit,manual_blueprint_join_support,cohort_blueprint_optional_join_identifier,NaN,0.000000,618,528,NaN,NaN,NaN,[fill in during cohort blueprint review]
16,optional_for_first_baseline,clinical,clinical_radiation,radiation_adjuvant_units,treatment_proxy_field,Preserve audited treatment-proxy fields as opt...,optional_case_level_treatment_proxy,True,clinical_shortlist,usable_treatment_proxy,treatment_proxy_direct_treatment_table,medium,0.092233,561,2,NaN,NaN,NaN,[fill in during cohort blueprint review]
17,optional_for_first_baseline,clinical,clinical_radiation,radiation_therapy_ended_days_to,treatment_proxy_field,Preserve audited treatment-proxy fields as opt...,optional_case_level_treatment_proxy,True,clinical_shortlist,usable_treatment_proxy,treatment_proxy_direct_treatment_table,medium,0.033981,597,275,NaN,NaN,NaN,[fill in during cohort blueprint review]
18,optional_for_first_baseline,clinical,clinical_radiation,radiation_therapy_ongoing_indicator,treatment_proxy_field,Preserve audited treatment-proxy fields as opt...,optional_case_level_treatment_proxy,True,clinical_shortlist,usable_treatment_proxy,treatment_proxy_direct_treatment_table,medium,0.009709,612,2,NaN,NaN,NaN,[fill in during cohort blueprint review]
19,optional_for_first_baseline,clinical,clinical_radiation,radiation_therapy_site,treatment_proxy_field,Preserve audited treatment-proxy fields as opt...,optional_case_level_treatment_proxy,True,clinical_shortlist,usable_treatment_proxy,treatment_proxy_direct_treatment_table,medium,0.032362,598,5,NaN,NaN,NaN,[fill in during cohort blueprint review]
20,optional_for_first_baseline,clinical,clinical_radiation,radiation_therapy_started_days_to,treatment_proxy_field,Preserve audited treatment-proxy fields as opt...,optional_case_level_treatment_proxy,True,clinical_shortlist,usable_treatment_proxy,treatment_proxy_direct_treatment_table,medium,0.038835,594,267,NaN,NaN,NaN,[fill in during cohort blueprint review]
21,optional_for_first_baseline,clinical,clinical_radiation,radiation_therapy_type,treatment_proxy_field,Preserve audited treatment-proxy fields as opt...,optional_case_level_treatment_proxy,True,clinical_shortlist,usable_treatment_proxy,treatment_proxy_direct_treatment_table,medium,0.030744,599,5,NaN,NaN,NaN,[fill in during cohort blueprint review]
22,optional_for_first_baseline,clinical,clinical_radiation,radiation_total_dose,treatment_proxy_field,Preserve audited treatment-proxy fields as opt...,optional_case_level_treatment_proxy,True,clinical_shortlist,usable_treatment_proxy,treatment_proxy_direct_treatment_table,medium,0.135922,534,127,NaN,NaN,NaN,[fill in during cohort blueprint review]
23,optional_for_first_baseline,endpoint,clinical_follow_up_v4_0,followup_lost_to,endpoint_candidate_join_preparation,Carry audited endpoint candidate fields only a...,case_to_endpoint_candidate_preparation,False,endpoint_crosswalk,primary_candidate,role_primary_best_usable_completeness,low,0.036313,690,2,NaN,role_primary_best_usable_completeness,NaN,[fill in during cohort blueprint review]
24,optional_for_first_baseline,endpoint,clinical_follow_up_v4_0,last_contact_days_to,endpoint_candidate_join_preparation,Carry audited endpoint candidate fields only a...,case_to_endpoint_candidate_preparation,False,endpoint_crosswalk,primary_candidate,role_primary_best_usable_completeness,medium,0.086592,654,551,NaN,role_primary_best_usable_completeness,NaN,[fill in during cohort blueprint review]
25,optional_for_first_baseline,endpoint,clinical_follow_up_v4_0,new_tumor_event_dx_indicator,endpoint_candidate_join_preparation,Carry audited endpoint candidate fields only a...,case_to_endpoint_candidate_preparation,False,endpoint_crosswalk,primary_candidate,role_primary_best_usable_completeness,medium,0.096369,647,2,NaN,role_primary_best_usable_completeness,NaN,[fill in during cohort blueprint review]
26,optional_for_first_baseline,endpoint,clinical_follow_up_v4_0,tumor_status,endpoint_candidate_join_preparation,Carry audited endpoint candidate fields only a...,case_to_endpoint_candidate_preparation,False,endpoint_crosswalk,primary_candidate,role_primary_best_usable_completeness,medium,0.054469,677,2,NaN,role_primary_best_usable_completeness,NaN,[fill in during cohort blueprint review]
27,optional_for_first_baseline,endpoint,clinical_follow_up_v4_0,vital_status,endpoint_candidate_join_preparation,Carry audited endpoint candidate fields only a...,case_to_endpoint_candidate_preparation,True,endpoint_crosswalk,overlapping_candidate,role_overlapping_same_canonical_signal,high,0.013966,706,2,NaN,role_overlapping_same_canonical_signal,NaN,[fill in during cohort blueprint review]
28,optional_for_first_baseline,endpoint,clinical_patient,last_contact_days_to,endpoint_candidate_join_preparation,Carry audited endpoint candidate fields only a...,case_to_endpoint_candidate_preparation,True,endpoint_crosswalk,overlapping_candidate,role_overlapping_same_canonical_signal,high,0.094804,993,649,NaN,role_overlapping_same_canonical_signal,NaN,[fill in during cohort blueprint review]
29,optional_for_first_baseline,endpoint,clinical_patient,new_tumor_event_dx_indicator,endpoint_candidate_join_preparation,Carry audited endpoint candidate fields only a...,case_to_endpoint_candidate_preparation,True,endpoint_crosswalk,overlapping_candidate,role_overlapping_same_canonical_signal,high,0.822242,195,2,NaN,role_overlapping_same_canonical_signal,NaN,[fill in during cohort blueprint review]
30,optional_for_first_baseline,endpoint,clinical_patient,tumor_status,endpoint_candidate_join_preparation,Carry audited endpoint candidate fields only a...,case_to_endpoint_candidate_preparation,True,endpoint_crosswalk,overlapping_candidate,role_overlapping_same_canonical_signal,high,0.113947,972,2,NaN,role_overlapping_same_canonical_signal,NaN,[fill in during cohort blueprint review]
31,optional_for_first_baseline,endpoint,clinical_patient,vital_status,endpoint_candidate_join_preparation,Carry audited endpoint candidate fields only a...,case_to_endpoint_candidate_preparation,False,endpoint_crosswalk,primary_candidate,role_primary_best_usable_completeness,medium,0.000000,1097,2,NaN,role_primary_best_usable_completeness,NaN,[fill in during cohort blueprint review]
32,optional_for_first_baseline,biospecimen,biospecimen_sample,days_to_sample_procurement,biospecimen_sample_helper,Retain audited sample helper fields as optiona...,sample_anchor_context_only,True,biospecimen_identifier_crosswalk,secondary_link_candidate,role_secondary_level_helper_field,medium,1.000000,0,0,bcr_sample_barcode,same_row_copresence_only,0.0,[fill in during cohort blueprint review]
33,optional_for_first_baseline,biospecimen,biospecimen_sample,method_of_sample_procurement,biospecimen_sample_helper,Retain audited sample helper fields as optiona...,sample_anchor_context_only,True,biospecimen_identifier_crosswalk,secondary_link_candidate,role_secondary_level_helper_field,medium,1.000000,0,0,bcr_sample_barcode,same_row_copresence_only,0.0,[fill in during cohort blueprint review]
34,optional_for_first_baseline,biospecimen,biospecimen_sample,other_method_of_sample_procurement,biospecimen_sample_helper,Retain audited sample helper fields as optiona...,sample_anchor_context_only,True,biospecimen_identifier_crosswalk,secondary_link_candidate,role_secondary_level_helper_field,medium,1.000000,0,0,bcr_sample_barcode,same_row_copresence_only,0.0,[fill in during cohort blueprint review]
35,optional_for_first_baseline,biospecimen,biospecimen_sample,sample_type,biospecimen_sample_helper,Retain audited sample helper fields as optiona...,sample_anchor_context_only,True,biospecimen_identifier_crosswalk,secondary_link_candidate,role_secondary_level_helper_field,medium,0.000000,2302,4,bcr_sample_barcode,same_row_copresence_only,1.0,[fill in during cohort blueprint review]
36,optional_for_first_baseline,biospecimen,biospecimen_sample,sample_type_id,biospecimen_sample_helper,Retain audited sample helper fields as optiona...,sample_anchor_context_only,True,biospecimen_identifier_crosswalk,secondary_link_candidate,role_secondary_level_helper_field,medium,0.000000,2302,4,bcr_sample_barcode,same_row_copresence_only,1.0,[fill in during cohort blueprint review]

,field_bucket,source_layer,table_name,field_name,proposed_role,rationale,dependency_for_join,ambiguity_flag,upstream_source_type,upstream_bucket_or_role,upstream_rule,manual_review_priority,missing_like_fraction,non_missing_count,distinct_non_missing_count,paired_field_name,evidence_rule,evidence_rate,notes_placeholder
0,deferred_for_later_expansion,endpoint,clinical_follow_up_v4_0,death_days_to,deferred_endpoint_candidate,Defer endpoint candidates that remain sparse o...,deferred_endpoint_resolution,True,endpoint_crosswalk,ambiguous_candidate,role_ambiguous_no_usable_primary_or_sparse_signal,high,0.927374,52,52,NaN,role_ambiguous_no_usable_primary_or_sparse_signal,NaN,[fill in during cohort blueprint review]
1,deferred_for_later_expansion,endpoint,clinical_patient,days_to_patient_progression_free,deferred_endpoint_candidate,Defer endpoint candidates that remain sparse o...,deferred_endpoint_resolution,True,endpoint_crosswalk,ambiguous_candidate,role_ambiguous_no_usable_primary_or_sparse_signal,high,1.000000,0,0,NaN,role_ambiguous_no_usable_primary_or_sparse_signal,NaN,[fill in during cohort blueprint review]
2,deferred_for_later_expansion,endpoint,clinical_patient,days_to_tumor_progression,deferred_endpoint_candidate,Defer endpoint candidates that remain sparse o...,deferred_endpoint_resolution,True,endpoint_crosswalk,ambiguous_candidate,role_ambiguous_no_usable_primary_or_sparse_signal,high,1.000000,0,0,NaN,role_ambiguous_no_usable_primary_or_sparse_signal,NaN,[fill in during cohort blueprint review]
3,deferred_for_later_expansion,endpoint,clinical_patient,death_days_to,deferred_endpoint_candidate,Defer endpoint candidates that remain sparse o...,deferred_endpoint_resolution,True,endpoint_crosswalk,ambiguous_candidate,role_ambiguous_no_usable_primary_or_sparse_signal,high,0.905196,104,101,NaN,role_ambiguous_no_usable_primary_or_sparse_signal,NaN,[fill in during cohort blueprint review]
4,deferred_for_later_expansion,biospecimen,biospecimen_aliquot,bcr_aliquot_barcode,child_biospecimen_identifier,Keep deeper biospecimen identifiers for later ...,later_child_layer_expansion,True,biospecimen_identifier_crosswalk,primary_link_candidate,role_primary_canonical_level_identifier,low,0.000000,14538,14538,bcr_aliquot_uuid,exact_pair_one_to_one_same_table,1.000000,[fill in during cohort blueprint review]
5,deferred_for_later_expansion,biospecimen,biospecimen_aliquot,bcr_aliquot_uuid,child_biospecimen_identifier,Keep deeper biospecimen identifiers for later ...,later_child_layer_expansion,True,biospecimen_identifier_crosswalk,primary_link_candidate,role_primary_canonical_level_identifier,low,0.000000,14538,14538,bcr_aliquot_barcode,exact_pair_one_to_one_same_table,1.000000,[fill in during cohort blueprint review]
6,deferred_for_later_expansion,biospecimen,biospecimen_aliquot,bcr_patient_uuid,later_biospecimen_side_or_overlap_identifier,Keep overlapping and side-table biospecimen id...,later_side_link_review,True,biospecimen_identifier_crosswalk,overlapping_link_candidate,role_overlapping_repeated_strong_identifier,medium,0.000000,14538,1101,bcr_sample_barcode,same_row_copresence_only,1.000000,[fill in during cohort blueprint review]
7,deferred_for_later_expansion,biospecimen,biospecimen_aliquot,bcr_sample_barcode,later_biospecimen_side_or_overlap_identifier,Keep overlapping and side-table biospecimen id...,later_side_link_review,True,biospecimen_identifier_crosswalk,overlapping_link_candidate,role_overlapping_repeated_strong_identifier,medium,0.000000,14538,2300,bcr_aliquot_barcode,barcode_prefix_same_row,0.999587,[fill in during cohort blueprint review]
8,deferred_for_later_expansion,biospecimen,biospecimen_aliquot,biospecimen_barcode_bottom,ambiguous_biospecimen_identifier,Keep deeper biospecimen identifiers for later ...,manual_identifier_review,True,biospecimen_identifier_crosswalk,ambiguous_candidate,role_ambiguous_generic_or_conflicted_identifier,high,0.000000,14538,14537,bcr_sample_barcode,same_row_copresence_only,1.000000,[fill in during cohort blueprint review]
9,deferred_for_later_expansion,biospecimen,biospecimen_analyte,analyte_type,child_biospecimen_identifier,Keep deeper biospecimen identifiers for later ...,later_child_layer_expansion,True,biospecimen_identifier_crosswalk,secondary_link_candidate,role_secondary_level_helper_field,medium,0.000000,6315,4,bcr_analyte_barcode,same_row_copresence_only,1.000000,[fill in during cohort blueprint review]
10,deferred_for_later_expansion,biospecimen,biospecimen_analyte,analyte_type_id,child_biospecimen_identifier,Keep deeper biospecimen identifiers for later ...,later_child_layer_expansion,True,biospecimen_identifier_crosswalk,secondary_link_candidate,role_secondary_level_helper_field,medium,0.000000,6315,4,bcr_analyte_barcode,same_row_copresence_only,1.000000,[fill in during cohort blueprint review]
11,deferred_for_later_expansion,biospecimen,biospecimen_analyte,bcr_analyte_barcode,child_biospecimen_identifier,Keep deeper biospecimen identifiers for later ...,later_child_layer_expansion,True,biospecimen_identifier_crosswalk,primary_link_candidate,role_primary_canonical_level_identifier,low,0.000000,6315,6315,bcr_analyte_uuid,exact_pair_one_to_one_same_table,1.000000,[fill in during cohort blueprint review]
12,deferred_for_later_expansion,biospecimen,biospecimen_analyte,bcr_analyte_uuid,child_biospecimen_identifier,Keep deeper biospecimen identifiers for later ...,later_child_layer_expansion,True,biospecimen_identifier_crosswalk,primary_link_candidate,role_primary_canonical_level_identifier,low,0.000000,6315,6315,bcr_analyte_barcode,exact_pair_one_to_one_same_table,1.000000,[fill in during cohort blueprint review]
13,deferred_for_later_expansion,biospecimen,biospecimen_analyte,bcr_patient_uuid,later_biospecimen_side_or_overlap_identifier,Keep overlapping and side-table biospecimen id...,later_side_link_review,True,biospecimen_identifier_crosswalk,overlapping_link_candidate,role_overlapping_repeated_strong_identifier,medium,0.000000,6315,1101,bcr_sample_barcode,same_row_copresence_only,1.000000,[fill in during cohort blueprint review]
14,deferred_for_later_expansion,biospecimen,biospecimen_analyte,bcr_sample_barcode,later_biospecimen_side_or_overlap_identifier,Keep overlapping and side-table biospecimen id...,later_side_link_review,True,biospecimen_identifier_crosswalk,overlapping_link_candidate,role_overlapping_repeated_strong_identifier,medium,0.000000,6315,2300,bcr_analyte_barcode,barcode_prefix_same_row,0.999367,[fill in during cohort blueprint review]
15,deferred_for_later_expansion,biospecimen,biospecimen_analyte,subportion_sequence,child_biospecimen_identifier,Keep deeper biospecimen identifiers for later ...,later_child_layer_expansion,True,biospecimen_identifier_crosswalk,secondary_link_candidate,role_secondary_level_helper_field,medium,0.365954,4004,4,bcr_sample_barcode,same_row_copresence_only,1.000000,[fill in during cohort blueprint review]
16,deferred_for_later_expansion,biospecimen,biospecimen_diagnostic_slides,bcr_patient_barcode,later_biospecimen_side_or_overlap_identifier,Carry forward any remaining audited biospecime...,later_side_link_review,True,biospecimen_identifier_crosswalk,primary_link_candidate,role_primary_patient_best_barcode_candidate,medium,0.000000,1142,1071,bcr_patient_uuid,exact_pair_one_to_one_same_table,1.000000,[fill in during cohort blueprint review]
17,deferred_for_later_expansion,biospecimen,biospecimen_diagnostic_slides,bcr_patient_uuid,later_biospecimen_side_or_overlap_identifier,Keep overlapping and side-table biospecimen id...,later_side_link_review,True,biospecimen_identifier_crosswalk,side_table_candidate,role_side_table_strong_identifier,medium,0.000000,1142,1071,bcr_patient_barcode,exact_pair_one_to_one_same_table,1.000000,[fill in during cohort blueprint review]
18,deferred_for_later_expansion,biospecimen,biospecimen_diagnostic_slides,bcr_sample_barcode,later_biospecimen_side_or_overlap_identifier,Keep overlapping and side-table biospecimen id...,later_side_link_review,True,biospecimen_identifier_crosswalk,side_table_candidate,role_side_table_strong_identifier,medium,0.000000,1142,1071,bcr_patient_barcode,barcode_prefix_same_row,1.000000,[fill in during cohort blueprint review]
19,deferred_for_later_expansion,biospecimen,biospecimen_diagnostic_slides,ffpe_slide_uuid,child_biospecimen_identifier,Keep deeper biospecimen identifiers for later ...,later_child_layer_expansion,True,biospecimen_identifier_crosswalk,side_table_candidate,role_side_table_strong_identifier,medium,0.000000,1142,1142,bcr_sample_barcode,same_row_copresence_only,1.000000,[fill in during cohort blueprint review]
20,deferred_for_later_expansion,biospecimen,biospecimen_portion,bcr_patient_uuid,later_biospecimen_side_or_overlap_identifier,Keep overlapping and side-table biospecimen id...,later_side_link_review,True,biospecimen_identifier_crosswalk,overlapping_link_candidate,role_overlapping_repeated_strong_identifier,medium,0.000000,2310,1101,bcr_sample_barcode,same_row_copresence_only,1.000000,[fill in during cohort blueprint review]
21,deferred_for_later_expansion,biospecimen,biospecimen_portion,bcr_portion_barcode,child_biospecimen_identifier,Keep deeper biospecimen identifiers for later ...,later_child_layer_expansion,True,biospecimen_identifier_crosswalk,primary_link_candidate,role_primary_canonical_level_identifier,low,0.000000,2310,2309,bcr_portion_uuid,exact_pair_one_to_one_same_table,1.000000,[fill in during cohort blueprint review]
22,deferred_for_later_expansion,biospecimen,biospecimen_portion,bcr_portion_uuid,child_biospecimen_identifier,Keep deeper biospecimen identifiers for later ...,later_child_layer_expansion,True,biospecimen_identifier_crosswalk,primary_link_candidate,role_primary_canonical_level_identifier,low,0.000000,2310,2309,bcr_portion_barcode,exact_pair_one_to_one_same_table,1.000000,[fill in during cohort blueprint review]
23,deferred_for_later_expansion,biospecimen,biospecimen_portion,bcr_sample_barcode,later_biospecimen_side_or_overlap_identifier,Keep overlapping and side-table biospecimen id...,later_side_link_review,True,biospecimen_identifier_crosswalk,overlapping_link_candidate,role_overlapping_repeated_strong_identifier,medium,0.000000,2310,2300,bcr_portion_barcode,barcode_prefix_same_row,1.000000,[fill in during cohort blueprint review]
24,deferred_for_later_expansion,biospecimen,biospecimen_portion,portion_number,child_biospecimen_identifier,Keep deeper biospecimen identifiers for later ...,later_child_layer_expansion,True,biospecimen_identifier_crosswalk,secondary_link_candidate,role_secondary_level_helper_field,medium,0.000000,2310,31,bcr_portion_barcode,same_row_copresence_only,1.000000,[fill in during cohort blueprint review]
25,deferred_for_later_expansion,biospecimen,biospecimen_portion,portion_sequence,child_biospecimen_identifier,Keep deeper biospecimen identifiers for later ...,later_child_layer_expansion,True,biospecimen_identifier_crosswalk,secondary_link_candidate,role_secondary_level_helper_field,medium,0.076190,2134,9,bcr_portion_barcode,same_row_copresence_only,1.000000,[fill in during cohort blueprint review]
26,deferred_for_later_expansion,biospecimen,biospecimen_protocol,bcr_analyte_barcode,child_biospecimen_identifier,Keep deeper biospecimen identifiers for later ...,later_child_layer_expansion,True,biospecimen_identifier_crosswalk,side_table_candidate,role_side_table_strong_identifier,medium,0.000000,6315,6315,bcr_sample_barcode,barcode_prefix_same_row,0.999367,[fill in during cohort blueprint review]
27,deferred_for_later_expansion,biospecimen,biospecimen_protocol,bcr_patient_uuid,later_biospecimen_side_or_overlap_identifier,Keep overlapping and side-table biospecimen id...,later_side_link_review,True,biospecimen_identifier_crosswalk,side_table_candidate,role_side_table_strong_identifier,medium,0.000000,6315,1101,bcr_sample_barcode,same_row_copresence_only,1.000000,[fill in during cohort blueprint review]
28,deferred_for_later_expansion,biospecimen,biospecimen_protocol,bcr_sample_barcode,later_biospecimen_side_or_overlap_identifier,Keep overlapping and side-table biospecimen id...,later_side_link_review,True,biospecimen_identifier_crosswalk,side_table_candidate,role_side_table_strong_identifier,medium,0.000000,6315,2300,bcr_analyte_barcode,barcode_prefix_same_row,0.999367,[fill in during cohort blueprint review]
29,deferred_for_later_expansion,biospecimen,biospecimen_sample,pathology_report_uuid,ambiguous_biospecimen_identifier,Keep deeper biospecimen identifiers for later ...,manual_identifier_review,True,biospecimen_identifier_crosswalk,ambiguous_candidate,role_ambiguous_generic_or_conflicted_identifier,high,0.513032,1121,1106,bcr_sample_barcode,same_row_copresence_only,1.000000,[fill in during cohort blueprint review]
30,deferred_for_later_expansion,biospecimen,biospecimen_shipment_portion,bcr_patient_uuid,later_biospecimen_side_or_overlap_identifier,Keep overlapping and side-table biospecimen id...,later_side_link_review,True,biospecimen_identifier_crosswalk,side_table_candidate,role_side_table_strong_identifier,medium,0.000000,1064,887,bcr_sample_barcode,same_row_copresence_only,1.000000,[fill in during cohort blueprint review]
31,deferred_for_later_expansion,biospecimen,biospecimen_shipment_portion,bcr_sample_barcode,later_biospecimen_side_or_overlap_identifier,Keep overlapping and side-table biospecimen id...,later_side_link_review,True,biospecimen_identifier_crosswalk,side_table_candidate,role_side_table_strong_identifier,medium,0.000000,1064,940,bcr_patient_uuid,same_row_copresence_only,1.000000,[fill in during cohort blueprint review]
32,deferred_for_later_expansion,biospecimen,biospecimen_shipment_portion,bcr_shipment_portion_uuid,child_biospecimen_identifier,Keep deeper biospecimen identifiers for later ...,later_child_layer_expansion,True,biospecimen_identifier_crosswalk,side_table_candidate,role_side_table_strong_identifier,medium,0.000000,1064,1064,bcr_sample_barcode,same_row_copresence_only,1.000000,[fill in during cohort blueprint review]
33,deferred_for_later_expansion,biospecimen,biospecimen_shipment_portion,portion_number,child_biospecimen_identifier,Keep deeper biospecimen identifiers for later ...,later_child_layer_expansion,True,biospecimen_identifier_crosswalk,secondary_link_candidate,role_secondary_level_helper_field,medium,0.000000,1064,15,bcr_shipment_portion_uuid,same_row_copresence_only,1.000000,[fill in during cohort blueprint review]
34,deferred_for_later_expansion,biospecimen,biospecimen_shipment_portion,portion_sequence,child_biospecimen_identifier,Keep deeper biospecimen identifiers for later ...,later_child_layer_expansion,True,biospecimen_identifier_crosswalk,secondary_link_candidate,role_secondary_level_helper_field,medium,0.022556,1040,9,bcr_shipment_portion_uuid,same_row_copresence_only,1.000000,[fill in during cohort blueprint review]
35,deferred_for_later_expansion,biospecimen,biospecimen_shipment_portion,shipment_portion_bcr_aliquot_barcode,ambiguous_biospecimen_identifier,Keep deeper biospecimen identifiers for later ...,manual_identifier_review,True,biospecimen_identifier_crosswalk,ambiguous_candidate,role_ambiguous_generic_or_conflicted_identifier,high,0.000000,1064,1064,bcr_sample_barcode,same_row_copresence_only,1.000000,[fill in during cohort blueprint review]
36,deferred_for_later_expansion,biospecimen,biospecimen_shipment_portion,shipment_portion_day_of_shipment,child_biospecimen_identifier,Keep deeper biospecimen identifiers for later ...,later_child_layer_expansion,True,biospecimen_identifier_crosswalk,secondary_link_candidate,role_secondary_level_helper_field,medium,0.000000,1064,6,bcr_shipment_portion_uuid,same_row_copresence_only,1.000000,[fill in during cohort blueprint review]
37,deferred_for_later_expansion,biospecimen,biospecimen_shipment_portion,shipment_portion_month_of_shipment,child_biospecimen_identifier,Keep deeper biospecimen identifiers for later ...,later_child_layer_expansion,True,biospecimen_identifier_crosswalk,secondary_link_candidate,role_secondary_level_helper_field,medium,0.000000,1064,6,bcr_shipment_portion_uuid,same_row_copresence_only,1.000000,[fill in during cohort blueprint review]
38,deferred_for_later_expansion,biospecimen,biospecimen_shipment_portion,shipment_portion_year_of_shipment,child_biospecimen_identifier,Keep deeper biospecimen identifiers for later ...,later_child_layer_expansion,True,biospecimen_identifier_crosswalk,secondary_link_candidate,role_secondary_level_helper_field,medium,0.000000,1064,4,bcr_shipment_portion_uuid,same_row_copresence_only,1.000000,[fill in during cohort blueprint review]
39,deferred_for_later_expansion,biospecimen,biospecimen_slide,bcr_patient_uuid,later_biospecimen_side_or_overlap_identifier,Keep overlapping and side-table biospecimen id...,later_side_link_review,True,biospecimen_identifier_crosswalk,overlapping_link_candidate,role_overlapping_repeated_strong_identifier,medium,0.000000,1995,1101,bcr_sample_barcode,same_row_copresence_only,1.000000,[fill in during cohort blueprint review]
40,deferred_for_later_expansion,biospecimen,biospecimen_slide,bcr_sample_barcode,later_biospecimen_side_or_overlap_identifier,Keep overlapping and side-table biospecimen id...,later_side_link_review,True,biospecimen_identifier_crosswalk,overlapping_link_candidate,role_overlapping_repeated_strong_identifier,medium,0.000000,1995,1283,bcr_slide_barcode,barcode_prefix_same_row,0.991479,[fill in during cohort blueprint review]
41,deferred_for_later_expansion,biospecimen,biospecimen_slide,bcr_slide_barcode,child_biospecimen_identifier,Keep deeper biospecimen identifiers for later ...,later_child_layer_expansion,True,biospecimen_identifier_crosswalk,primary_link_candidate,role_primary_canonical_level_identifier,low,0.000000,1995,1991,bcr_slide_uuid,exact_pair_one_to_one_same_table,1.000000,[fill in during cohort blueprint review]
42,deferred_for_later_expansion,biospecimen,biospecimen_slide,bcr_slide_uuid,child_biospecimen_identifier,Keep deeper biospecimen identifiers for later ...,later_child_layer_expansion,True,biospecimen_identifier_crosswalk,primary_link_candidate,role_primary_canonical_level_identifier,low,0.000000,1995,1991,bcr_slide_barcode,exact_pair_one_to_one_same_table,1.000000,[fill in during cohort blueprint review]

## Save join-path, ambiguity, and summary review tables

In [5]:
join_path_review_df = (
    join_path_df[
        [
            'step_order',
            'left_node',
            'right_node',
            'left_table_name',
            'right_table_name',
            'left_field_name',
            'right_field_name',
            'join_keys_or_evidence',
            'join_strength',
            'link_timing',
            'rationale',
            'ambiguity_flag',
            'notes_placeholder',
        ]
    ]
    .sort_values(['step_order'], ascending=[True])
    .reset_index(drop=True)
)
join_path_review_path = results_root / '51_cohort_blueprint_join_path.tsv'
join_path_review_df.to_csv(join_path_review_path, sep='\t', index=False)

ambiguity_review_df = (
    ambiguity_df[
        [
            'ambiguity_id',
            'ambiguity_category',
            'source_layer',
            'table_name',
            'field_name_or_step',
            'severity',
            'why_unresolved',
            'current_saved_evidence',
            'proposed_blueprint_handling',
            'blocks_final_cohort_construction',
            'notes_placeholder',
        ]
    ]
    .sort_values(['severity', 'ambiguity_id'], ascending=[True, True])
    .reset_index(drop=True)
)
ambiguity_review_path = results_root / '52_cohort_blueprint_ambiguities.tsv'
ambiguity_review_df.to_csv(ambiguity_review_path, sep='\t', index=False)

summary_review_df = summary_df.sort_values(['summary_section', 'summary_metric']).reset_index(drop=True)
summary_review_path = results_root / '53_cohort_blueprint_summary.tsv'
summary_review_df.to_csv(summary_review_path, sep='\t', index=False)

print(f'Saved: {join_path_review_path}')
print(f'Saved: {ambiguity_review_path}')
print(f'Saved: {summary_review_path}')
display(join_path_review_df)
display(ambiguity_review_df)
display(summary_review_df)

Saved: D:\Projects\brcapath-rx\09-trials\01-tcga-only-source-audited\05-results\51_cohort_blueprint_join_path.tsv
Saved: D:\Projects\brcapath-rx\09-trials\01-tcga-only-source-audited\05-results\52_cohort_blueprint_ambiguities.tsv
Saved: D:\Projects\brcapath-rx\09-trials\01-tcga-only-source-audited\05-results\53_cohort_blueprint_summary.tsv

,step_order,left_node,right_node,left_table_name,right_table_name,left_field_name,right_field_name,join_keys_or_evidence,join_strength,link_timing,rationale,ambiguity_flag,notes_placeholder
0,1,patient/case,clinical_patient,NaN,clinical_patient,case_identifier,bcr_patient_barcode / bcr_patient_uuid,clinical_patient carries both audited case ide...,strong_current_evidence,link_now,Use clinical_patient as the central case-level...,False,[fill in during cohort blueprint review]
1,2,patient/case,clinical_drug,clinical_patient,clinical_drug,bcr_patient_barcode / bcr_patient_uuid,bcr_patient_barcode / bcr_patient_uuid,clinical_drug contains repeated patient identi...,workable_but_needs_review,link_later,Treatment rows can be attached later as option...,True,[fill in during cohort blueprint review]
2,3,patient/case,clinical_radiation,clinical_patient,clinical_radiation,bcr_patient_barcode / bcr_patient_uuid,bcr_patient_barcode / bcr_patient_uuid,clinical_radiation contains repeated patient i...,workable_but_needs_review,link_later,Radiation rows should remain optional treatmen...,True,[fill in during cohort blueprint review]
3,4,patient/case,clinical_patient endpoint-like fields,clinical_patient,clinical_patient,bcr_patient_barcode / bcr_patient_uuid,vital_status / last_contact_days_to / tumor_st...,clinical_patient endpoint-like fields already ...,strong_current_evidence,prepare_only,Patient-table endpoint candidates can be carri...,False,[fill in during cohort blueprint review]
4,5,patient/case,clinical_follow_up_v4_0 endpoint-like fields,clinical_patient,clinical_follow_up_v4_0,bcr_patient_barcode / bcr_patient_uuid,bcr_patient_barcode / bcr_patient_uuid,follow-up endpoint-like fields reuse patient i...,workable_but_needs_review,prepare_only,Follow-up endpoint candidates are usable for l...,True,[fill in during cohort blueprint review]
5,6,patient/case,biospecimen_sample,clinical_patient,biospecimen_sample,bcr_patient_uuid / bcr_patient_barcode,bcr_patient_uuid / bcr_sample_barcode / bcr_sa...,biospecimen_sample provides the main specimen ...,workable_but_needs_review,link_now,The blueprint can anchor on biospecimen_sample...,True,[fill in during cohort blueprint review]
6,7,sample,portion,biospecimen_sample,biospecimen_portion,bcr_sample_barcode / bcr_sample_uuid,bcr_sample_barcode / bcr_portion_barcode / bcr...,biospecimen_portion repeats bcr_sample_barcode...,strong_current_evidence,link_later,Sample-to-portion is the strongest saved child...,False,[fill in during cohort blueprint review]
7,8,portion,analyte,biospecimen_portion,biospecimen_analyte,bcr_portion_barcode / bcr_portion_uuid,bcr_analyte_barcode / bcr_analyte_uuid / subpo...,analyte rows retain sample barcode plus subpor...,workable_but_needs_review,link_later,Portion-to-analyte looks workable but still ne...,True,[fill in during cohort blueprint review]
8,9,analyte,slide,biospecimen_analyte,biospecimen_slide,bcr_analyte_barcode / bcr_analyte_uuid,bcr_slide_barcode / bcr_slide_uuid / bcr_sampl...,No direct saved analyte identifier appears in ...,deferred,link_later,An analyte-to-slide step should remain deferre...,True,[fill in during cohort blueprint review]
9,10,analyte,aliquot,biospecimen_analyte,biospecimen_aliquot,bcr_analyte_barcode / bcr_analyte_uuid,bcr_aliquot_barcode / bcr_aliquot_uuid / bcr_s...,No direct saved analyte identifier appears in ...,deferred,link_later,An analyte-to-aliquot step should remain defer...,True,[fill in during cohort blueprint review]
10,11,sample/analyte,protocol,biospecimen_sample / biospecimen_analyte,biospecimen_protocol,bcr_sample_barcode / bcr_analyte_barcode,bcr_sample_barcode / bcr_analyte_barcode,biospecimen_protocol carries both sample and a...,workable_but_needs_review,link_later,Protocol remains a side-link layer that looks ...,True,[fill in during cohort blueprint review]
11,12,sample/portion,shipment_portion,biospecimen_sample / biospecimen_portion,biospecimen_shipment_portion,bcr_sample_barcode / portion_number / portion_...,bcr_shipment_portion_uuid / bcr_sample_barcode...,shipment_portion retains sample barcode plus p...,workable_but_needs_review,link_later,Shipment data can support later specimen-track...,True,[fill in during cohort blueprint review]
12,13,sample/slide,diagnostic_slides,biospecimen_sample / biospecimen_slide,biospecimen_diagnostic_slides,bcr_sample_barcode / bcr_slide_barcode,bcr_sample_barcode / ffpe_slide_uuid / bcr_pat...,diagnostic_slides provides sample and patient ...,deferred,link_later,Diagnostic slide linkage should remain deferre...,True,[fill in during cohort blueprint review]

,ambiguity_id,ambiguity_category,source_layer,table_name,field_name_or_step,severity,why_unresolved,current_saved_evidence,proposed_blueprint_handling,blocks_final_cohort_construction,notes_placeholder
0,A01,endpoint_overlap_patient_vs_followup,endpoint,clinical_patient | clinical_follow_up_v4_0,vital_status,high,The same endpoint-like field exists in both pa...,clinical_patient.vital_status has 1097 non-mis...,Carry both rows as endpoint join-preparation f...,True,[fill in during cohort blueprint review]
1,A02,endpoint_overlap_patient_vs_followup,endpoint,clinical_patient | clinical_follow_up_v4_0,last_contact_days_to,high,Patient and follow-up tables both carry last-c...,clinical_patient.last_contact_days_to has 993 ...,Keep both rows optional and endpoint-preparato...,True,[fill in during cohort blueprint review]
2,A03,endpoint_overlap_patient_vs_followup,endpoint,clinical_patient | clinical_follow_up_v4_0,tumor_status,high,Tumor-status signals overlap across patient an...,clinical_patient.tumor_status has 972 non-miss...,Preserve both rows for later endpoint review a...,True,[fill in during cohort blueprint review]
3,A04,endpoint_overlap_patient_vs_followup,endpoint,clinical_patient | clinical_follow_up_v4_0,new_tumor_event_dx_indicator,high,New-tumor-event indicators overlap across pati...,clinical_patient.new_tumor_event_dx_indicator ...,Keep both rows as later endpoint-reconciliatio...,True,[fill in during cohort blueprint review]
4,A05,sparse_endpoint_timing,endpoint,clinical_patient | clinical_follow_up_v4_0,death_days_to,high,Death timing exists in both tables but remains...,clinical_patient.death_days_to has 104 non-mis...,Record death timing as deferred endpoint evide...,True,[fill in during cohort blueprint review]
5,A06,all_missing_progression_timing,endpoint,clinical_patient,days_to_patient_progression_free | days_to_tum...,high,Progression timing fields were surfaced only a...,Both progression timing fields have 0 non-miss...,Keep both fields deferred and exclude them fro...,True,[fill in during cohort blueprint review]
6,A07,clinical_vs_biospecimen_patient_identifiers,clinical | biospecimen,clinical_patient | biospecimen_sample | biospe...,bcr_patient_barcode | bcr_patient_uuid,high,Clinical and biospecimen layers expose both pa...,clinical_patient has 1097 non-missing values f...,Use both identifier forms as evidence-bearing ...,True,[fill in during cohort blueprint review]
7,A08,case_count_mismatch,clinical | source | biospecimen,clinical_patient | source_metadata | biospecim...,case coverage counts,high,"The saved clinical, source-acquisition, and bi...",clinical_patient row count is 1097; clinical s...,Flag cross-layer case counts as a blocking rec...,True,[fill in during cohort blueprint review]
8,A09,treatment_table_multiplicity,clinical,clinical_drug | clinical_radiation,patient-linked treatment rows,medium,Treatment tables are one-to-many and include o...,clinical_drug has 2406 rows over 780 distinct ...,Keep treatment fields optional and proxy-only ...,False,[fill in during cohort blueprint review]
9,A10,missing_direct_child_link,biospecimen,biospecimen_analyte | biospecimen_slide,analyte -> slide,medium,The saved biospecimen crosswalk does not expos...,biospecimen_slide retains sample barcode and s...,Keep analyte-to-slide deferred and use sample-...,False,[fill in during cohort blueprint review]
10,A11,missing_direct_child_link,biospecimen,biospecimen_analyte | biospecimen_aliquot,analyte -> aliquot,medium,The saved biospecimen crosswalk does not expos...,biospecimen_aliquot carries sample barcode and...,Keep analyte-to-aliquot deferred and revisit i...,False,[fill in during cohort blueprint review]

,blueprint_run_id,summary_section,summary_metric,summary_value,notes
0,20260413T081835Z,ambiguities,ambiguity_count,11,Total unresolved issues recorded by the bluepr...
1,20260413T081835Z,ambiguities,blocking_ambiguity_count,8,Ambiguities currently marked as blocking final...
2,20260413T081835Z,count_signals,biospecimen_patient_uuid_distinct_count,1101,Distinct patient UUID count from the biospecim...
3,20260413T081835Z,count_signals,biospecimen_sample_anchor_count,2302,Sample-anchor row count from the biospecimen c...
4,20260413T081835Z,count_signals,clinical_patient_case_count,1097,clinical_patient row count from the saved clin...
5,20260413T081835Z,count_signals,clinical_source_case_submitter_coverage,1098,Unique clinical source case coverage computed ...
6,20260413T081835Z,design,endpoint_policy,candidate_join_preparation_only,Endpoint rows remain preparatory only; the fin...
7,20260413T081835Z,design,proposed_biospecimen_anchor,sample,biospecimen_sample is the required specimen an...
8,20260413T081835Z,design,proposed_unit_of_analysis,patient/case,The first baseline blueprint keeps the analysi...
9,20260413T081835Z,design,treatment_policy,proxy_only_optional,Treatment rows remain optional proxy evidence ...
10,20260413T081835Z,field_counts,deferred_field_count,43,Deferred later-expansion or unresolved fields.
11,20260413T081835Z,field_counts,deferred_for_later_expansion_biospecimen_count,39,deferred_for_later_expansion rows carried from...
12,20260413T081835Z,field_counts,deferred_for_later_expansion_clinical_count,0,deferred_for_later_expansion rows carried from...
13,20260413T081835Z,field_counts,deferred_for_later_expansion_endpoint_count,4,deferred_for_later_expansion rows carried from...
14,20260413T081835Z,field_counts,optional_field_count,37,Optional attach-later first-study fields.
15,20260413T081835Z,field_counts,optional_for_first_baseline_biospecimen_count,5,optional_for_first_baseline rows carried from ...
16,20260413T081835Z,field_counts,optional_for_first_baseline_clinical_count,23,optional_for_first_baseline rows carried from ...
17,20260413T081835Z,field_counts,optional_for_first_baseline_endpoint_count,9,optional_for_first_baseline rows carried from ...
18,20260413T081835Z,field_counts,required_field_count,32,Required first-baseline fields across clinical...
19,20260413T081835Z,field_counts,required_for_first_baseline_biospecimen_count,3,required_for_first_baseline rows carried from ...
20,20260413T081835Z,field_counts,required_for_first_baseline_clinical_count,29,required_for_first_baseline rows carried from ...
21,20260413T081835Z,field_counts,required_for_first_baseline_endpoint_count,0,required_for_first_baseline rows carried from ...
22,20260413T081835Z,join_path,deferred_count,3,Join steps marked as deferred.
23,20260413T081835Z,join_path,join_step_count,13,Total fixed join/path blueprint steps.
24,20260413T081835Z,join_path,link_later_count,9,Join steps marked as link_later.
25,20260413T081835Z,join_path,link_now_count,2,Join steps marked as link_now.
26,20260413T081835Z,join_path,prepare_only_count,2,Join steps marked as prepare_only.
27,20260413T081835Z,join_path,strong_current_evidence_count,3,Join steps marked as strong_current_evidence.
28,20260413T081835Z,join_path,workable_but_needs_review_count,7,Join steps marked as workable_but_needs_review.
29,20260413T081835Z,upstream_runs,biospecimen_crosswalk_run_id,20260413T073640Z,Biospecimen identifier crosswalk run used by t...
30,20260413T081835Z,upstream_runs,biospecimen_parse_run_id,20260413T070359Z,Biospecimen biotab parse run behind the biospe...
31,20260413T081835Z,upstream_runs,clinical_core_audit_run_id,20260412T023839Z,Clinical core audit run referenced by the curr...
32,20260413T081835Z,upstream_runs,clinical_parse_run_id,20260412T010932Z,Clinical biotab parse run behind the current s...
33,20260413T081835Z,upstream_runs,clinical_shortlist_run_id,20260412T033602Z,Current clinical shortlist run used by the blu...
34,20260413T081835Z,upstream_runs,endpoint_crosswalk_run_id,20260412T042036Z,Endpoint crosswalk run used by the blueprint.
35,20260413T081835Z,upstream_runs,shared_source_run_id_count,1,Count of unique source_run_id values across th...

## Review reminder

These outputs remain a blueprint and study-design layer only. They do not create a final cohort table, freeze the endpoint, harmonize model-ready variables, parse new raw files, or perform modeling.